export const IDENTITY_ADDITIONAL_TRANSACTION_TYPES = {
  UPDATE_ROLE: 'IDENTITY_UPDATE_ROLE',

  CREATE_STAFF: 'IDENTITY_CREATE_STAFF',
  UPDATE_STAFF: 'IDENTITY_UPDATE_STAFF',

  CREATE_USER: 'IDENTITY_CREATE_USER',
  UPDATE_USER: 'IDENTITY_UPDATE_USER',
  RESET_USER_PASSWORD: 'IDENTITY_RESET_USER_PASSWORD',
  REPLACE_USER_ROLES: 'IDENTITY_REPLACE_USER_ROLES',
} as const;

export const IDENTITY_COMPENSATION_TYPES = {
  DELETE_CREATED_ROLE: 'IDENTITY_DELETE_CREATED_ROLE',
  RESTORE_ROLE: 'IDENTITY_RESTORE_ROLE',

  DELETE_CREATED_ROLE_PERMISSION:
    'IDENTITY_DELETE_CREATED_ROLE_PERMISSION',

  RESTORE_ROLE_PERMISSION:
    'IDENTITY_RESTORE_ROLE_PERMISSION',

  DELETE_CREATED_STAFF:
    'IDENTITY_DELETE_CREATED_STAFF',

  RESTORE_STAFF:
    'IDENTITY_RESTORE_STAFF',

  DELETE_CREATED_USER:
    'IDENTITY_DELETE_CREATED_USER',

  RESTORE_USER:
    'IDENTITY_RESTORE_USER',

  DELETE_CREATED_USER_ROLE:
    'IDENTITY_DELETE_CREATED_USER_ROLE',

  RESTORE_USER_ROLE:
    'IDENTITY_RESTORE_USER_ROLE',
} as const;

export const IDENTITY_TRANSACTION_CHECKPOINTS = {
  VALIDATED: 'VALIDATED',

  ROLE_CREATED: 'ROLE_CREATED',
  ROLE_UPDATED: 'ROLE_UPDATED',
  PERMISSIONS_APPLIED: 'PERMISSIONS_APPLIED',

  STAFF_CREATED: 'STAFF_CREATED',
  STAFF_UPDATED: 'STAFF_UPDATED',

  PASSWORD_HASHED: 'PASSWORD_HASHED',
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_ROLES_APPLIED: 'USER_ROLES_APPLIED',
  USER_PASSWORD_UPDATED: 'USER_PASSWORD_UPDATED',
  USER_SESSIONS_REVOKED: 'USER_SESSIONS_REVOKED',

  AUDIT_APPENDED: 'AUDIT_APPENDED',
  OUTBOX_ENQUEUED: 'OUTBOX_ENQUEUED',
} as const;