import type {
  ClinicalNoteRecord,
  EncounterDiagnosisRecord,
  EncounterRecord,
  PatientAllergyRecord,
  PatientProblemRecord,
} from './clinical-emr.types.js';

export const ENCOUNTER_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'encounterNumber',
  'patientId',
  'requestedPatientId',
  'canonicalRedirected',
  'registrationId',
  'opdVisitId',
  'queueTokenId',
  'emergencyCaseId',
  'admissionId',
  'referralId',
  'encounterType',
  'careContext',
  'status',
  'serviceDate',
  'departmentId',
  'clinicId',
  'servicePointId',
  'primaryProviderId',
  'currentOwnerId',
  'currentOwnerRole',
  'assignedProviderIds',
  'confidentiality',
  'startedAt',
  'lastClinicalActivityAt',
  'completedAt',
  'signedAt',
  'signedBy',
  'closedAt',
  'closedBy',
  'cancelledAt',
  'cancelledBy',
  'supersedesEncounterId',
  'supersededByEncounterId',
  'amendmentCount',
  'latestClinicalNoteId',
  'latestDiagnosisAt',
  'transactionId',
  'correlationId',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const ENCOUNTER_INTERNAL_SELECT = [
  ENCOUNTER_STANDARD_SELECT,
  '+restrictionReason',
  '+activeContextKey',
  '+signatureDigest',
  '+cancellationReason',
  '+correctionReason',
].join(' ');

export const ENCOUNTER_STATUS_HISTORY_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'encounterId',
  'patientId',
  'sequence',
  'fromStatus',
  'toStatus',
  'previousOwnerId',
  'newOwnerId',
  'previousOwnerRole',
  'newOwnerRole',
  'changeSource',
  'occurredAt',
  'changedBy',
  'transactionId',
  'correlationId',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const ENCOUNTER_STATUS_HISTORY_INTERNAL_SELECT = [
  ENCOUNTER_STATUS_HISTORY_STANDARD_SELECT,
  '+reason',
].join(' ');

export const CLINICAL_NOTE_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'noteNumber',
  'encounterId',
  'patientId',
  'authorProviderId',
  'documentType',
  'title',
  'status',
  'confidentiality',
  'currentVersion',
  'latestVersionId',
  'finalizedAt',
  'finalizedBy',
  'signedAt',
  'signedBy',
  'signatureMethod',
  'amendedAt',
  'amendedBy',
  'correctedAt',
  'correctedBy',
  'enteredInErrorAt',
  'enteredInErrorBy',
  'addendumToNoteId',
  'supersedesNoteId',
  'supersededByNoteId',
  'transactionId',
  'correlationId',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const CLINICAL_NOTE_CONTENT_SELECT = [
  CLINICAL_NOTE_STANDARD_SELECT,
  '+narrativeText',
  '+structuredData',
  '+restrictionReason',
  '+signatureDigest',
  '+amendmentReason',
  '+correctionReason',
  '+enteredInErrorReason',
].join(' ');

export const CLINICAL_NOTE_VERSION_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'clinicalNoteId',
  'encounterId',
  'patientId',
  'versionNumber',
  'previousVersionId',
  'changeType',
  'statusSnapshot',
  'documentTypeSnapshot',
  'confidentialitySnapshot',
  'snapshotHash',
  'contentHash',
  'authorProviderId',
  'signedBy',
  'signatureMethod',
  'recordedAt',
  'recordedBy',
  'transactionId',
  'correlationId',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const CLINICAL_NOTE_VERSION_INTERNAL_SELECT = [
  CLINICAL_NOTE_VERSION_STANDARD_SELECT,
  '+encryptedSnapshot',
  '+changeReason',
  '+signatureDigest',
].join(' ');

export const DIAGNOSIS_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'codeSystem',
  'code',
  'normalizedCode',
  'display',
  'normalizedDisplay',
  'synonyms',
  'description',
  'parentDiagnosisId',
  'billable',
  'status',
  'deactivatedAt',
  'deactivatedBy',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const DIAGNOSIS_INTERNAL_SELECT = [
  DIAGNOSIS_STANDARD_SELECT,
  '+deactivationReason',
].join(' ');

export const ENCOUNTER_DIAGNOSIS_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'encounterId',
  'patientId',
  'diagnosisId',
  'codeSystem',
  'code',
  'normalizedCode',
  'display',
  'role',
  'certainty',
  'status',
  'clinicalNoteId',
  'onsetDate',
  'resolvedAt',
  'isChronic',
  'presentOnAdmission',
  'recordedAt',
  'recordedBy',
  'verifiedAt',
  'verifiedBy',
  'supersedesEncounterDiagnosisId',
  'supersededByEncounterDiagnosisId',
  'transactionId',
  'correlationId',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const ENCOUNTER_DIAGNOSIS_INTERNAL_SELECT = [
  ENCOUNTER_DIAGNOSIS_STANDARD_SELECT,
  '+activeDiagnosisKey',
  '+evidence',
  '+statusReason',
].join(' ');

export const PATIENT_PROBLEM_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'problemNumber',
  'patientId',
  'diagnosisId',
  'sourceEncounterId',
  'sourceEncounterDiagnosisId',
  'codeSystem',
  'code',
  'normalizedCode',
  'display',
  'status',
  'onsetDate',
  'resolvedAt',
  'currentVersion',
  'latestVersionId',
  'supersedesProblemId',
  'supersededByProblemId',
  'recordedAt',
  'recordedBy',
  'transactionId',
  'correlationId',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const PATIENT_PROBLEM_CONTENT_SELECT = [
  PATIENT_PROBLEM_STANDARD_SELECT,
  '+activeProblemKey',
  '+summary',
  '+statusReason',
].join(' ');

export const PATIENT_PROBLEM_VERSION_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'patientProblemId',
  'patientId',
  'versionNumber',
  'previousVersionId',
  'changeType',
  'statusSnapshot',
  'snapshotHash',
  'recordedAt',
  'recordedBy',
  'transactionId',
  'correlationId',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const PATIENT_PROBLEM_VERSION_INTERNAL_SELECT = [
  PATIENT_PROBLEM_VERSION_STANDARD_SELECT,
  '+encryptedSnapshot',
  '+changeReason',
].join(' ');

export const ALLERGY_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'code',
  'category',
  'name',
  'normalizedName',
  'synonyms',
  'description',
  'status',
  'deactivatedAt',
  'deactivatedBy',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const ALLERGY_INTERNAL_SELECT = [
  ALLERGY_STANDARD_SELECT,
  '+deactivationReason',
].join(' ');

export const PATIENT_ALLERGY_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'patientId',
  'recordType',
  'allergyId',
  'category',
  'allergenText',
  'normalizedAllergenText',
  'status',
  'verificationStatus',
  'severity',
  'onsetDate',
  'lastReactionAt',
  'clinicalNoteId',
  'sourceEncounterId',
  'currentVersion',
  'latestVersionId',
  'recordedAt',
  'recordedBy',
  'verifiedAt',
  'verifiedBy',
  'supersedesPatientAllergyId',
  'supersededByPatientAllergyId',
  'transactionId',
  'correlationId',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const PATIENT_ALLERGY_CONTENT_SELECT = [
  PATIENT_ALLERGY_STANDARD_SELECT,
  '+reactions',
  '+notes',
  '+activeAllergyKey',
  '+statusReason',
].join(' ');

export const PATIENT_ALLERGY_VERSION_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'patientAllergyId',
  'patientId',
  'versionNumber',
  'previousVersionId',
  'statusSnapshot',
  'snapshotHash',
  'recordedAt',
  'recordedBy',
  'transactionId',
  'correlationId',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const PATIENT_ALLERGY_VERSION_INTERNAL_SELECT = [
  PATIENT_ALLERGY_VERSION_STANDARD_SELECT,
  '+encryptedSnapshot',
  '+changeReason',
].join(' ');

export function encounterAuditSnapshot(
  record: EncounterRecord,
): Record<string, unknown> {
  return {
    encounterId: record._id.toHexString(),
    encounterNumber: record.encounterNumber,
    patientId: record.patientId.toHexString(),
    requestedPatientId: record.requestedPatientId.toHexString(),
    canonicalRedirected: record.canonicalRedirected,
    registrationId: record.registrationId?.toHexString() ?? null,
    opdVisitId: record.opdVisitId?.toHexString() ?? null,
    queueTokenId: record.queueTokenId?.toHexString() ?? null,
    admissionId: record.admissionId?.toHexString() ?? null,
    encounterType: record.encounterType,
    careContext: record.careContext,
    status: record.status,
    serviceDate: record.serviceDate,
    departmentId: record.departmentId.toHexString(),
    clinicId: record.clinicId?.toHexString() ?? null,
    servicePointId: record.servicePointId?.toHexString() ?? null,
    primaryProviderId: record.primaryProviderId.toHexString(),
    currentOwnerId: record.currentOwnerId.toHexString(),
    currentOwnerRole: record.currentOwnerRole,
    assignedProviderIds: record.assignedProviderIds.map(
      (providerId) => providerId.toHexString(),
    ),
    confidentiality: record.confidentiality,
    startedAt: record.startedAt.toISOString(),
    completedAt: record.completedAt?.toISOString() ?? null,
    signedAt: record.signedAt?.toISOString() ?? null,
    closedAt: record.closedAt?.toISOString() ?? null,
    cancelledAt: record.cancelledAt?.toISOString() ?? null,
    version: record.version,
  };
}

export function clinicalNoteAuditSnapshot(
  record: ClinicalNoteRecord,
): Record<string, unknown> {
  return {
    clinicalNoteId: record._id.toHexString(),
    noteNumber: record.noteNumber,
    encounterId: record.encounterId.toHexString(),
    patientId: record.patientId.toHexString(),
    authorProviderId: record.authorProviderId.toHexString(),
    documentType: record.documentType,
    status: record.status,
    confidentiality: record.confidentiality,
    currentVersion: record.currentVersion,
    finalizedAt: record.finalizedAt?.toISOString() ?? null,
    signedAt: record.signedAt?.toISOString() ?? null,
    amendedAt: record.amendedAt?.toISOString() ?? null,
    correctedAt: record.correctedAt?.toISOString() ?? null,
    enteredInErrorAt: record.enteredInErrorAt?.toISOString() ?? null,
    addendumToNoteId: record.addendumToNoteId?.toHexString() ?? null,
    supersedesNoteId: record.supersedesNoteId?.toHexString() ?? null,
    supersededByNoteId: record.supersededByNoteId?.toHexString() ?? null,
    version: record.version,
  };
}

export function encounterDiagnosisAuditSnapshot(
  record: EncounterDiagnosisRecord,
): Record<string, unknown> {
  return {
    encounterDiagnosisId: record._id.toHexString(),
    encounterId: record.encounterId.toHexString(),
    patientId: record.patientId.toHexString(),
    diagnosisId: record.diagnosisId?.toHexString() ?? null,
    role: record.role,
    certainty: record.certainty,
    status: record.status,
    isChronic: record.isChronic,
    presentOnAdmission: record.presentOnAdmission,
    recordedAt: record.recordedAt.toISOString(),
    verifiedAt: record.verifiedAt?.toISOString() ?? null,
    version: record.version,
  };
}

export function patientProblemAuditSnapshot(
  record: PatientProblemRecord,
): Record<string, unknown> {
  return {
    patientProblemId: record._id.toHexString(),
    problemNumber: record.problemNumber,
    patientId: record.patientId.toHexString(),
    diagnosisId: record.diagnosisId?.toHexString() ?? null,
    sourceEncounterId: record.sourceEncounterId.toHexString(),
    status: record.status,
    currentVersion: record.currentVersion,
    resolvedAt: record.resolvedAt?.toISOString() ?? null,
    supersedesProblemId: record.supersedesProblemId?.toHexString() ?? null,
    supersededByProblemId: record.supersededByProblemId?.toHexString() ?? null,
    version: record.version,
  };
}

export function patientAllergyAuditSnapshot(
  record: PatientAllergyRecord,
): Record<string, unknown> {
  return {
    patientAllergyId: record._id.toHexString(),
    patientId: record.patientId.toHexString(),
    recordType: record.recordType,
    allergyId: record.allergyId?.toHexString() ?? null,
    category: record.category,
    status: record.status,
    verificationStatus: record.verificationStatus,
    severity: record.severity,
    currentVersion: record.currentVersion,
    sourceEncounterId: record.sourceEncounterId?.toHexString() ?? null,
    verifiedAt: record.verifiedAt?.toISOString() ?? null,
    supersedesPatientAllergyId:
      record.supersedesPatientAllergyId?.toHexString() ?? null,
    supersededByPatientAllergyId:
      record.supersededByPatientAllergyId?.toHexString() ?? null,
    version: record.version,
  };
}