export const MEDICINE_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'medicineCode',
  'genericName',
  'normalizedGenericName',
  'brandNames',
  'synonyms',
  'therapeuticClass',
  'atcCode',
  'description',
  'status',
  'deactivatedAt',
  'deactivatedBy',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const MEDICINE_INTERNAL_SELECT = [
  MEDICINE_STANDARD_SELECT,
  '+deactivationReason',
].join(' ');

export const MEDICINE_FORM_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'code',
  'name',
  'normalizedName',
  'category',
  'status',
  'deactivatedAt',
  'deactivatedBy',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const MEDICINE_FORM_INTERNAL_SELECT = [
  MEDICINE_FORM_STANDARD_SELECT,
  '+deactivationReason',
].join(' ');

export const MEDICINE_ROUTE_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'code',
  'name',
  'normalizedName',
  'status',
  'deactivatedAt',
  'deactivatedBy',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const MEDICINE_ROUTE_INTERNAL_SELECT = [
  MEDICINE_ROUTE_STANDARD_SELECT,
  '+deactivationReason',
].join(' ');

export const UNIT_OF_MEASURE_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'code',
  'name',
  'normalizedName',
  'symbol',
  'dimension',
  'decimalScale',
  'status',
  'deactivatedAt',
  'deactivatedBy',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const UNIT_OF_MEASURE_INTERNAL_SELECT = [
  UNIT_OF_MEASURE_STANDARD_SELECT,
  '+deactivationReason',
].join(' ');

export const MEDICINE_STRENGTH_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'medicineId',
  'medicineFormId',
  'displayText',
  'normalizedDisplayText',
  'numeratorValue',
  'numeratorUnitId',
  'denominatorValue',
  'denominatorUnitId',
  'status',
  'deactivatedAt',
  'deactivatedBy',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const MEDICINE_STRENGTH_INTERNAL_SELECT = [
  MEDICINE_STRENGTH_STANDARD_SELECT,
  '+deactivationReason',
].join(' ');

export const PRESCRIPTION_FREQUENCY_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'code',
  'name',
  'normalizedName',
  'kind',
  'timesPerDay',
  'intervalMinutes',
  'defaultAdministrationTimes',
  'allowsAsNeeded',
  'maxAdministrationsPerDay',
  'patientInstructionTemplate',
  'status',
  'deactivatedAt',
  'deactivatedBy',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const PRESCRIPTION_FREQUENCY_INTERNAL_SELECT = [
  PRESCRIPTION_FREQUENCY_STANDARD_SELECT,
  '+deactivationReason',
].join(' ');

export const FORMULARY_ITEM_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'formularyCode',
  'medicineId',
  'medicineFormId',
  'medicineStrengthId',
  'brandName',
  'normalizedBrandName',
  'allowedRouteIds',
  'defaultRouteId',
  'doseUnitId',
  'quantityUnitId',
  'inventoryItemId',
  'stockTracked',
  'restrictionType',
  'restrictedDepartmentIds',
  'minimumAgeYears',
  'maximumAgeYears',
  'highAlert',
  'controlledMedicine',
  'searchText',
  'effectiveFrom',
  'effectiveUntil',
  'status',
  'deactivatedAt',
  'deactivatedBy',
  'transactionId',
  'correlationId',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const FORMULARY_ITEM_INTERNAL_SELECT = [
  FORMULARY_ITEM_STANDARD_SELECT,
  '+prescribingNotes',
  '+activeSelectionKey',
  '+deactivationReason',
].join(' ');

export const PRESCRIPTION_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'prescriptionNumber',
  'patientId',
  'requestedPatientId',
  'canonicalRedirected',
  'encounterId',
  'registrationId',
  'opdVisitId',
  'queueTokenId',
  'departmentId',
  'clinicId',
  'servicePointId',
  'prescriberProviderId',
  'status',
  'revisionNumber',
  'rootPrescriptionId',
  'supersedesPrescriptionId',
  'supersededByPrescriptionId',
  'draftedAt',
  'issuedAt',
  'expiresAt',
  'signedBy',
  'signatureMethod',
  'lockedAt',
  'lockedBy',
  'cancelledAt',
  'cancelledBy',
  'interactionCheckStatus',
  'interactionCheckProvider',
  'interactionCheckedAt',
  'itemCount',
  'activeItemCount',
  'dispensedItemCount',
  'safetyWarningCount',
  'unresolvedBlockingWarningCount',
  'printRevision',
  'lastPrintedAt',
  'lastPrintedBy',
  'transactionId',
  'correlationId',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const PRESCRIPTION_INTERNAL_SELECT = [
  PRESCRIPTION_STANDARD_SELECT,
  '+replacementReason',
  '+signatureDigest',
  '+issuedSnapshotHash',
  '+cancellationReason',
].join(' ');

export const PRESCRIPTION_ITEM_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'prescriptionId',
  'patientId',
  'encounterId',
  'sequence',
  'formularyItemId',
  'medicineId',
  'medicineFormId',
  'medicineStrengthId',
  'selectedBrandName',
  'genericNameSnapshot',
  'medicineFormSnapshot',
  'medicineStrengthSnapshot',
  'dose',
  'doseUnitId',
  'doseUnitSnapshot',
  'routeId',
  'routeSnapshot',
  'frequencyId',
  'frequencySnapshot',
  'durationValue',
  'durationUnit',
  'quantity',
  'quantityUnitId',
  'quantityUnitSnapshot',
  'asNeeded',
  'startDate',
  'endDate',
  'status',
  'cancelledAt',
  'cancelledBy',
  'dispensedQuantity',
  'lastDispensedAt',
  'lastDispensationId',
  'transactionId',
  'correlationId',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const PRESCRIPTION_ITEM_CONTENT_SELECT = [
  PRESCRIPTION_ITEM_STANDARD_SELECT,
  '+instructions',
  '+asNeededReason',
  '+cancellationReason',
].join(' ');

export const PRESCRIPTION_WARNING_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'prescriptionId',
  'prescriptionItemId',
  'patientId',
  'encounterId',
  'warningType',
  'severity',
  'status',
  'warningCode',
  'patientAllergyId',
  'conflictingPrescriptionId',
  'conflictingPrescriptionItemId',
  'detectedAt',
  'detectedBy',
  'acknowledgedAt',
  'acknowledgedBy',
  'overriddenAt',
  'overriddenBy',
  'resolvedAt',
  'resolvedBy',
  'transactionId',
  'correlationId',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const PRESCRIPTION_WARNING_CONTENT_SELECT = [
  PRESCRIPTION_WARNING_STANDARD_SELECT,
  '+warningFingerprint',
  '+message',
  '+externalReferenceId',
  '+acknowledgementReason',
  '+overrideReason',
  '+resolutionReason',
].join(' ');

export const PRESCRIPTION_HISTORY_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'prescriptionId',
  'patientId',
  'sequence',
  'fromStatus',
  'toStatus',
  'changeType',
  'changeSource',
  'snapshotHash',
  'signedBy',
  'signatureMethod',
  'occurredAt',
  'changedBy',
  'transactionId',
  'correlationId',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const PRESCRIPTION_HISTORY_INTERNAL_SELECT = [
  PRESCRIPTION_HISTORY_STANDARD_SELECT,
  '+reason',
  '+encryptedSnapshot',
  '+signatureDigest',
].join(' ');