export const FACILITY_TRANSACTION_TYPES = {
  CREATE_FACILITY:
    'FACILITY_CONFIGURATION_CREATE_FACILITY',

  UPDATE_FACILITY:
    'FACILITY_CONFIGURATION_UPDATE_FACILITY',

  ACTIVATE_FACILITY:
    'FACILITY_CONFIGURATION_ACTIVATE_FACILITY',

  DEACTIVATE_FACILITY:
    'FACILITY_CONFIGURATION_DEACTIVATE_FACILITY',

  CREATE_DEPARTMENT:
    'FACILITY_CONFIGURATION_CREATE_DEPARTMENT',

  UPDATE_DEPARTMENT:
    'FACILITY_CONFIGURATION_UPDATE_DEPARTMENT',

  ACTIVATE_DEPARTMENT:
    'FACILITY_CONFIGURATION_ACTIVATE_DEPARTMENT',

  DEACTIVATE_DEPARTMENT:
    'FACILITY_CONFIGURATION_DEACTIVATE_DEPARTMENT',

  CREATE_SETTING_DEFINITION:
    'FACILITY_CONFIGURATION_CREATE_SETTING_DEFINITION',

  UPDATE_SETTING_DEFINITION:
    'FACILITY_CONFIGURATION_UPDATE_SETTING_DEFINITION',

  UPSERT_SYSTEM_SETTING:
    'FACILITY_CONFIGURATION_UPSERT_SYSTEM_SETTING',
} as const;

export const FACILITY_COMPENSATION_TYPES = {
  DELETE_CREATED_FACILITY:
    'FACILITY_CONFIGURATION_DELETE_CREATED_FACILITY',

  RESTORE_FACILITY:
    'FACILITY_CONFIGURATION_RESTORE_FACILITY',

  RESTORE_FACILITY_LIFECYCLE:
    'FACILITY_CONFIGURATION_RESTORE_FACILITY_LIFECYCLE',

  DELETE_CREATED_DEPARTMENT:
    'FACILITY_CONFIGURATION_DELETE_CREATED_DEPARTMENT',

  RESTORE_DEPARTMENT:
    'FACILITY_CONFIGURATION_RESTORE_DEPARTMENT',

  RESTORE_DEPARTMENT_LIFECYCLE:
    'FACILITY_CONFIGURATION_RESTORE_DEPARTMENT_LIFECYCLE',

  DELETE_CREATED_SETTING_DEFINITION:
    'FACILITY_CONFIGURATION_DELETE_CREATED_SETTING_DEFINITION',

  RESTORE_SETTING_DEFINITION:
    'FACILITY_CONFIGURATION_RESTORE_SETTING_DEFINITION',

  DELETE_CREATED_SYSTEM_SETTING:
    'FACILITY_CONFIGURATION_DELETE_CREATED_SYSTEM_SETTING',

  RESTORE_SYSTEM_SETTING:
    'FACILITY_CONFIGURATION_RESTORE_SYSTEM_SETTING',

  DELETE_SYSTEM_SETTING_VERSION:
    'FACILITY_CONFIGURATION_DELETE_SYSTEM_SETTING_VERSION',
} as const;

export const FACILITY_TRANSACTION_CHECKPOINTS = {
  FACILITY_CREATED:
    'FACILITY_CREATED',

  FACILITY_UPDATED:
    'FACILITY_UPDATED',

  FACILITY_ACTIVATED:
    'FACILITY_ACTIVATED',

  FACILITY_DEACTIVATED:
    'FACILITY_DEACTIVATED',

  FACILITY_SESSIONS_REVOKED:
    'FACILITY_SESSIONS_REVOKED',

  DEPARTMENT_CREATED:
    'DEPARTMENT_CREATED',

  DEPARTMENT_UPDATED:
    'DEPARTMENT_UPDATED',

  DEPARTMENT_ACTIVATED:
    'DEPARTMENT_ACTIVATED',

  DEPARTMENT_DEACTIVATED:
    'DEPARTMENT_DEACTIVATED',

  SETTING_DEFINITION_CREATED:
    'SETTING_DEFINITION_CREATED',

  SETTING_DEFINITION_UPDATED:
    'SETTING_DEFINITION_UPDATED',

  SYSTEM_SETTING_CREATED:
    'SYSTEM_SETTING_CREATED',

  SYSTEM_SETTING_UPDATED:
    'SYSTEM_SETTING_UPDATED',

  SYSTEM_SETTING_VERSION_APPENDED:
    'SYSTEM_SETTING_VERSION_APPENDED',

  AUDIT_APPENDED:
    'AUDIT_APPENDED',

  OUTBOX_ENQUEUED:
    'OUTBOX_ENQUEUED',
} as const;

export const FACILITY_AUDIT_ACTIONS = {
  FACILITY_CREATED:
    'facility.created',

  FACILITY_UPDATED:
    'facility.updated',

  FACILITY_ACTIVATED:
    'facility.activated',

  FACILITY_DEACTIVATED:
    'facility.deactivated',

  DEPARTMENT_CREATED:
    'department.created',

  DEPARTMENT_UPDATED:
    'department.updated',

  DEPARTMENT_ACTIVATED:
    'department.activated',

  DEPARTMENT_DEACTIVATED:
    'department.deactivated',

  SETTING_DEFINITION_CREATED:
    'configuration.definition.created',

  SETTING_DEFINITION_UPDATED:
    'configuration.definition.updated',

  SYSTEM_SETTING_CREATED:
    'configuration.setting.created',

  SYSTEM_SETTING_UPDATED:
    'configuration.setting.updated',
} as const;

export const FACILITY_OUTBOX_EVENTS = {
  FACILITY_CREATED:
    'facility.created',

  FACILITY_UPDATED:
    'facility.updated',

  FACILITY_ACTIVATED:
    'facility.activated',

  FACILITY_DEACTIVATED:
    'facility.deactivated',

  DEPARTMENT_CREATED:
    'department.created',

  DEPARTMENT_UPDATED:
    'department.updated',

  DEPARTMENT_ACTIVATED:
    'department.activated',

  DEPARTMENT_DEACTIVATED:
    'department.deactivated',

  SETTING_DEFINITION_CREATED:
    'configuration.definition.created',

  SETTING_DEFINITION_UPDATED:
    'configuration.definition.updated',

  SYSTEM_SETTING_CREATED:
    'configuration.setting.created',

  SYSTEM_SETTING_UPDATED:
    'configuration.setting.updated',
} as const;

export const FACILITY_RECOVERY_MODES = {
  COMPENSATE:
    'COMPENSATE',

  FINALIZE_COMPLETED:
    'FINALIZE_COMPLETED',
} as const;

export type FacilityRecoveryMode =
  (typeof FACILITY_RECOVERY_MODES)[keyof typeof FACILITY_RECOVERY_MODES];