export const PHARMACY_DISPENSATION_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'dispensationNumber',
  'creationOperationKey',
  'prescriptionId',
  'prescriptionNumberSnapshot',
  'prescriptionRevisionNumber',
  'prescriptionVersion',
  'patientId',
  'requestedPatientId',
  'encounterId',
  'registrationId',
  'opdVisitId',
  'admissionId',
  'wardId',
  'departmentId',
  'servicePointId',
  'prescriberProviderId',
  'pharmacyLocationId',
  'sourceStockLocationId',
  'context',
  'priority',
  'status',
  'lineCount',
  'verifiedLineCount',
  'completedLineCount',
  'controlledMedicine',
  'highAlertMedicine',
  'secondCheckRequired',
  'witnessRequired',
  'stockReservationId',
  'queuedAt',
  'reviewStartedAt',
  'verifiedAt',
  'verifiedByStaffId',
  'secondCheckedAt',
  'secondCheckedByStaffId',
  'firstDispensedAt',
  'completedAt',
  'dispensedByStaffId',
  'heldAt',
  'heldByStaffId',
  'rejectedAt',
  'rejectedByStaffId',
  'cancelledAt',
  'cancelledByStaffId',
  'enteredInErrorAt',
  'enteredInErrorByStaffId',
  'expiredAt',
  'expiresAt',
  'currency',
  'grossAmount',
  'discountAmount',
  'taxAmount',
  'netAmount',
  'billingSourceRecordId',
  'finalizationState',
  'finalizationAttemptCount',
  'finalizationUpdatedAt',
  'attachmentIds',
  'transactionId',
  'correlationId',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const PHARMACY_DISPENSATION_INTERNAL_SELECT = [
  PHARMACY_DISPENSATION_STANDARD_SELECT,
  '+holdReason',
  '+rejectionReason',
  '+cancellationReason',
  '+enteredInErrorReason',
  '+billingOperationKey',
  '+recoveryReason',
  '+lastFailureCode',
].join(' ');

export const PHARMACY_DISPENSATION_ITEM_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'dispensationId',
  'prescriptionId',
  'prescriptionItemId',
  'patientId',
  'lineNumber',
  'prescribedFormularyItemId',
  'prescribedMedicineId',
  'prescribedMedicineFormId',
  'prescribedMedicineStrengthId',
  'prescribedRouteId',
  'prescribedFrequencyId',
  'prescribedMedicineSnapshot',
  'prescribedStrengthSnapshot',
  'prescribedFormSnapshot',
  'prescribedRouteSnapshot',
  'prescribedFrequencySnapshot',
  'prescribedQuantity',
  'prescribedQuantityUnitId',
  'requestedQuantity',
  'approvedQuantity',
  'reservedQuantity',
  'dispensedQuantity',
  'returnedQuantity',
  'reversedQuantity',
  'dispensedQuantityUnitId',
  'actualFormularyItemId',
  'actualMedicineId',
  'actualMedicineFormId',
  'actualMedicineStrengthId',
  'actualInventoryItemId',
  'actualMedicineSnapshot',
  'actualStrengthSnapshot',
  'actualFormSnapshot',
  'substitutionId',
  'substitutionApplied',
  'quantityRoundingApplied',
  'specialHandling',
  'controlledMedicine',
  'highAlertMedicine',
  'safetyAlerts.alertFingerprint',
  'safetyAlerts.alertType',
  'safetyAlerts.severity',
  'safetyAlerts.disposition',
  'safetyAlerts.code',
  'safetyAlerts.detectedAt',
  'safetyAlerts.acknowledgedByStaffId',
  'safetyAlerts.acknowledgedAt',
  'blockingAlertCount',
  'allocations',
  'unitSellingPrice',
  'grossAmount',
  'discountAmount',
  'taxAmount',
  'netAmount',
  'pricingSource',
  'priceOverrideApplied',
  'priceOverrideApprovedByStaffId',
  'status',
  'verifiedByStaffId',
  'verifiedAt',
  'dispensedByStaffId',
  'dispensedAt',
  'transactionId',
  'correlationId',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const PHARMACY_DISPENSATION_ITEM_INTERNAL_SELECT = [
  PHARMACY_DISPENSATION_ITEM_STANDARD_SELECT,
  '+prescribedInstructionsSnapshot',
  '+safetyAlerts.message',
  '+safetyAlerts.acknowledgementReason',
  '+quantityRoundingReason',
  '+priceOverrideReason',
  '+holdReason',
  '+rejectionReason',
].join(' ');

export const PHARMACY_REVIEW_EVENT_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'dispensationId',
  'dispensationItemId',
  'prescriptionId',
  'patientId',
  'scope',
  'action',
  'outcome',
  'reviewerStaffId',
  'checkerStaffId',
  'safetyAlerts.alertFingerprint',
  'safetyAlerts.alertType',
  'safetyAlerts.severity',
  'safetyAlerts.disposition',
  'safetyAlerts.code',
  'safetyAlerts.detectedAt',
  'blockingAlertCount',
  'occurredAt',
  'transactionId',
  'correlationId',
  'createdAt',
].join(' ');

export const PHARMACY_REVIEW_EVENT_INTERNAL_SELECT = [
  PHARMACY_REVIEW_EVENT_STANDARD_SELECT,
  '+reason',
  '+safetyAlerts.message',
  '+safetyAlerts.acknowledgementReason',
].join(' ');

export const PHARMACY_PRESCRIPTION_DISPENSING_SELECT = [
  '_id',
  'facilityId',
  'prescriptionNumber',
  'patientId',
  'requestedPatientId',
  'encounterId',
  'registrationId',
  'opdVisitId',
  'departmentId',
  'servicePointId',
  'prescriberProviderId',
  'status',
  'revisionNumber',
  'supersededByPrescriptionId',
  'issuedAt',
  'expiresAt',
  'interactionCheckStatus',
  'unresolvedBlockingWarningCount',
  'version',
].join(' ');

export const PHARMACY_PRESCRIPTION_ITEM_DISPENSING_SELECT = [
  '_id',
  'facilityId',
  'prescriptionId',
  'patientId',
  'encounterId',
  'sequence',
  'formularyItemId',
  'medicineId',
  'medicineFormId',
  'medicineStrengthId',
  'genericNameSnapshot',
  'medicineFormSnapshot',
  'medicineStrengthSnapshot',
  'routeId',
  'routeSnapshot',
  'frequencyId',
  'frequencySnapshot',
  'quantity',
  'quantityUnitId',
  'quantityUnitSnapshot',
  '+instructions',
  'status',
  'dispensedQuantity',
  'lastDispensedAt',
  'lastDispensationId',
  'version',
].join(' ');

export const PHARMACY_CONTROLLED_REGISTER_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'registerNumber',
  'registerSequence',
  'entryType',
  'direction',
  'pharmacyLocationId',
  'stockLocationId',
  'patientId',
  'prescriptionId',
  'dispensationId',
  'dispensationItemId',
  'pharmacistStaffId',
  'witnessRequired',
  'witnessStaffId',
  'inventoryItemId',
  'inventoryBatchId',
  'batchNumberSnapshot',
  'expiryDateSnapshot',
  'stockUnitId',
  'quantity',
  'openingBalance',
  'closingBalance',
  'physicalBalance',
  'stockMovementId',
  'discrepancyStatus',
  'discrepancyQuantity',
  'escalationReference',
  'occurredAt',
  'transactionId',
  'correlationId',
  'createdAt',
].join(' ');

export const PHARMACY_CONTROLLED_REGISTER_INTERNAL_SELECT = [
  PHARMACY_CONTROLLED_REGISTER_STANDARD_SELECT,
  '+operationKey',
  '+discrepancyReason',
  '+reason',
].join(' ');