export const PATIENT_TRANSACTION_TYPES = {
  REGISTER_PATIENT:
    'PATIENT_GUARDIAN_REGISTER_PATIENT',

  UPDATE_PATIENT:
    'PATIENT_GUARDIAN_UPDATE_PATIENT',

  UPDATE_GUARDIAN:
    'PATIENT_GUARDIAN_UPDATE_GUARDIAN',

  ADD_PATIENT_IDENTIFIER:
    'PATIENT_GUARDIAN_ADD_PATIENT_IDENTIFIER',

  VERIFY_PATIENT_IDENTIFIER:
    'PATIENT_GUARDIAN_VERIFY_PATIENT_IDENTIFIER',

  REVOKE_PATIENT_IDENTIFIER:
    'PATIENT_GUARDIAN_REVOKE_PATIENT_IDENTIFIER',

  LINK_PATIENT_GUARDIAN:
    'PATIENT_GUARDIAN_LINK_PATIENT_GUARDIAN',

  VERIFY_PATIENT_GUARDIAN:
    'PATIENT_GUARDIAN_VERIFY_PATIENT_GUARDIAN',

  END_PATIENT_GUARDIAN:
    'PATIENT_GUARDIAN_END_PATIENT_GUARDIAN',

  ADD_PATIENT_CONTACT:
    'PATIENT_GUARDIAN_ADD_PATIENT_CONTACT',

  UPDATE_PATIENT_CONTACT:
    'PATIENT_GUARDIAN_UPDATE_PATIENT_CONTACT',

  VERIFY_PATIENT_CONTACT:
    'PATIENT_GUARDIAN_VERIFY_PATIENT_CONTACT',

  DEACTIVATE_PATIENT_CONTACT:
    'PATIENT_GUARDIAN_DEACTIVATE_PATIENT_CONTACT',

  ADD_PATIENT_ADDRESS:
    'PATIENT_GUARDIAN_ADD_PATIENT_ADDRESS',

  UPDATE_PATIENT_ADDRESS:
    'PATIENT_GUARDIAN_UPDATE_PATIENT_ADDRESS',

  DEACTIVATE_PATIENT_ADDRESS:
    'PATIENT_GUARDIAN_DEACTIVATE_PATIENT_ADDRESS',

  CREATE_PATIENT_ALERT:
    'PATIENT_GUARDIAN_CREATE_PATIENT_ALERT',

  RESOLVE_PATIENT_ALERT:
    'PATIENT_GUARDIAN_RESOLVE_PATIENT_ALERT',

  RESOLVE_DUPLICATE_REVIEW:
    'PATIENT_GUARDIAN_RESOLVE_DUPLICATE_REVIEW',

  MERGE_PATIENTS:
    'PATIENT_GUARDIAN_MERGE_PATIENTS',
} as const;

export const PATIENT_COMPENSATION_TYPES = {
  DELETE_CREATED_PATIENT:
    'PATIENT_GUARDIAN_DELETE_CREATED_PATIENT',

  DELETE_CREATED_PATIENT_IDENTIFIER:
    'PATIENT_GUARDIAN_DELETE_CREATED_PATIENT_IDENTIFIER',

  DELETE_CREATED_GUARDIAN:
    'PATIENT_GUARDIAN_DELETE_CREATED_GUARDIAN',

  DELETE_CREATED_PATIENT_GUARDIAN:
    'PATIENT_GUARDIAN_DELETE_CREATED_PATIENT_GUARDIAN',

  DELETE_CREATED_PATIENT_CONTACT:
    'PATIENT_GUARDIAN_DELETE_CREATED_PATIENT_CONTACT',

  DELETE_CREATED_PATIENT_ADDRESS:
    'PATIENT_GUARDIAN_DELETE_CREATED_PATIENT_ADDRESS',

  DELETE_CREATED_PATIENT_ALERT:
    'PATIENT_GUARDIAN_DELETE_CREATED_PATIENT_ALERT',

  DELETE_CREATED_PATIENT_MERGE:
    'PATIENT_GUARDIAN_DELETE_CREATED_PATIENT_MERGE',

  RESTORE_PATIENT:
    'PATIENT_GUARDIAN_RESTORE_PATIENT',

  RESTORE_GUARDIAN:
    'PATIENT_GUARDIAN_RESTORE_GUARDIAN',

  RESTORE_PATIENT_IDENTIFIER:
    'PATIENT_GUARDIAN_RESTORE_PATIENT_IDENTIFIER',

  RESTORE_PATIENT_GUARDIAN:
    'PATIENT_GUARDIAN_RESTORE_PATIENT_GUARDIAN',

  RESTORE_PATIENT_CONTACT:
    'PATIENT_GUARDIAN_RESTORE_PATIENT_CONTACT',

  RESTORE_PATIENT_ADDRESS:
    'PATIENT_GUARDIAN_RESTORE_PATIENT_ADDRESS',

  RESTORE_PATIENT_ALERT:
    'PATIENT_GUARDIAN_RESTORE_PATIENT_ALERT',
} as const;

export const PATIENT_TRANSACTION_CHECKPOINTS = {
  DUPLICATE_CHECK_COMPLETED:
    'DUPLICATE_CHECK_COMPLETED',

  PATIENT_CREATED:
    'PATIENT_CREATED',

  PATIENT_UPDATED:
    'PATIENT_UPDATED',

  DUPLICATE_REVIEW_STATE_APPLIED:
    'DUPLICATE_REVIEW_STATE_APPLIED',

  DUPLICATE_REVIEW_RESOLVED:
    'DUPLICATE_REVIEW_RESOLVED',

  MRN_ALLOCATED:
    'MRN_ALLOCATED',

  IDENTIFIERS_CREATED:
    'IDENTIFIERS_CREATED',

  PATIENT_IDENTIFIER_CREATED:
    'PATIENT_IDENTIFIER_CREATED',

  PATIENT_IDENTIFIER_VERIFIED:
    'PATIENT_IDENTIFIER_VERIFIED',

  PATIENT_IDENTIFIER_REVOKED:
    'PATIENT_IDENTIFIER_REVOKED',

  GUARDIAN_RESOLVED:
    'GUARDIAN_RESOLVED',

  GUARDIAN_UPDATED:
    'GUARDIAN_UPDATED',

  GUARDIAN_LINKED:
    'GUARDIAN_LINKED',

  GUARDIAN_VERIFIED:
    'GUARDIAN_VERIFIED',

  GUARDIAN_ENDED:
    'GUARDIAN_ENDED',

  CONTACTS_CREATED:
    'CONTACTS_CREATED',

  PATIENT_CONTACT_CREATED:
    'PATIENT_CONTACT_CREATED',

  PATIENT_CONTACT_UPDATED:
    'PATIENT_CONTACT_UPDATED',

  PATIENT_CONTACT_VERIFIED:
    'PATIENT_CONTACT_VERIFIED',

  PATIENT_CONTACT_DEACTIVATED:
    'PATIENT_CONTACT_DEACTIVATED',

  ADDRESSES_CREATED:
    'ADDRESSES_CREATED',

  PATIENT_ADDRESS_CREATED:
    'PATIENT_ADDRESS_CREATED',

  PATIENT_ADDRESS_UPDATED:
    'PATIENT_ADDRESS_UPDATED',

  PATIENT_ADDRESS_DEACTIVATED:
    'PATIENT_ADDRESS_DEACTIVATED',

  PATIENT_ALERT_CREATED:
    'PATIENT_ALERT_CREATED',

  PATIENT_ALERT_RESOLVED:
    'PATIENT_ALERT_RESOLVED',

  MERGE_SOURCE_MARKED:
    'MERGE_SOURCE_MARKED',

  MERGE_TARGET_CONFIRMED:
    'MERGE_TARGET_CONFIRMED',

  PATIENT_MERGE_RECORDED:
    'PATIENT_MERGE_RECORDED',

  OUTBOX_ENQUEUED:
    'OUTBOX_ENQUEUED',

  AUDIT_APPENDED:
    'AUDIT_APPENDED',
} as const;

export const PATIENT_AUDIT_ACTIONS = {
  PATIENT_REGISTERED:
    'patient.registered',

  PATIENT_UPDATED:
    'patient.updated',

  GUARDIAN_UPDATED:
    'guardian.updated',

  PATIENT_IDENTIFIER_ADDED:
    'patient.identifier.added',

  PATIENT_IDENTIFIER_VERIFIED:
    'patient.identifier.verified',

  PATIENT_IDENTIFIER_REVOKED:
    'patient.identifier.revoked',

  PATIENT_GUARDIAN_LINKED:
    'patient.guardian.linked',

  PATIENT_GUARDIAN_VERIFIED:
    'patient.guardian.verified',

  PATIENT_GUARDIAN_ENDED:
    'patient.guardian.ended',

  PATIENT_CONTACT_ADDED:
    'patient.contact.added',

  PATIENT_CONTACT_UPDATED:
    'patient.contact.updated',

  PATIENT_CONTACT_VERIFIED:
    'patient.contact.verified',

  PATIENT_CONTACT_DEACTIVATED:
    'patient.contact.deactivated',

  PATIENT_ADDRESS_ADDED:
    'patient.address.added',

  PATIENT_ADDRESS_UPDATED:
    'patient.address.updated',

  PATIENT_ADDRESS_DEACTIVATED:
    'patient.address.deactivated',

  PATIENT_ALERT_CREATED:
    'patient.alert.created',

  PATIENT_ALERT_RESOLVED:
    'patient.alert.resolved',

  PATIENT_DUPLICATE_REVIEW_RESOLVED:
    'patient.duplicate_review.resolved',

  PATIENTS_MERGED:
    'patient.merged',
} as const;

export const PATIENT_OUTBOX_EVENTS = {
  PATIENT_REGISTERED:
    'patient.registered',

  PATIENT_UPDATED:
    'patient.updated',

  GUARDIAN_UPDATED:
    'guardian.updated',

  PATIENT_IDENTIFIER_ADDED:
    'patient.identifier.added',

  PATIENT_IDENTIFIER_VERIFIED:
    'patient.identifier.verified',

  PATIENT_IDENTIFIER_REVOKED:
    'patient.identifier.revoked',

  PATIENT_GUARDIAN_LINKED:
    'patient.guardian.linked',

  PATIENT_GUARDIAN_VERIFIED:
    'patient.guardian.verified',

  PATIENT_GUARDIAN_ENDED:
    'patient.guardian.ended',

  PATIENT_CONTACT_ADDED:
    'patient.contact.added',

  PATIENT_CONTACT_UPDATED:
    'patient.contact.updated',

  PATIENT_CONTACT_VERIFIED:
    'patient.contact.verified',

  PATIENT_CONTACT_DEACTIVATED:
    'patient.contact.deactivated',

  PATIENT_ADDRESS_ADDED:
    'patient.address.added',

  PATIENT_ADDRESS_UPDATED:
    'patient.address.updated',

  PATIENT_ADDRESS_DEACTIVATED:
    'patient.address.deactivated',

  PATIENT_ALERT_CREATED:
    'patient.alert.created',

  PATIENT_ALERT_RESOLVED:
    'patient.alert.resolved',

  PATIENT_DUPLICATE_REVIEW_RESOLVED:
    'patient.duplicate_review.resolved',

  PATIENTS_MERGED:
    'patient.merged',
} as const;

export const PATIENT_RECOVERY_MODES = {
  COMPENSATE:
    'COMPENSATE',

  FINALIZE_COMPLETED:
    'FINALIZE_COMPLETED',
} as const;

export type PatientRecoveryMode =
  (typeof PATIENT_RECOVERY_MODES)[keyof typeof PATIENT_RECOVERY_MODES];