import type {
  Db,
  IndexDescription,
} from 'mongodb';

import {
  collectionSpecs,
  type CollectionRetention,
  type HospitalCollectionName,
} from '../catalog/collection-specs.js';

import {
  ChargeCatalogModel,
  ChargeCatalogVersionModel,
  ChargeCategoryModel,
  ChargeRuleModel,
} from '../models/charge-catalog.model.js';

import {
  PackageEnrollmentModel,
  PackageUtilizationModel,
  PriceListModel,
  PriceListVersionModel,
  ServiceRateModel,
  TaxCategoryModel,
  TreatmentPackageItemModel,
  TreatmentPackageModel,
} from '../models/billing-pricing-package.model.js';

import {
  AccountChargeHistoryModel,
  AccountChargeModel,
  PatientAccountModel,
  PatientAccountStatusHistoryModel,
} from '../models/patient-account-charge.model.js';

import {
  CreditNoteModel,
  DebitNoteModel,
  DiscountApprovalModel,
  DiscountModel,
  FinancialApprovalRequestModel,
  InvoiceLineModel,
  InvoiceModel,
  InvoiceStatusHistoryModel,
} from '../models/billing-invoice-adjustment.model.js';

import {
  DepositModel,
  PaymentAllocationModel,
  PaymentIntentModel,
  PaymentModel,
  PaymentReversalModel,
  RefundModel,
  RefundRequestModel,
} from '../models/billing-payment.model.js';

import {
  FinancialLedgerAccountModel,
  FinancialLedgerEntryModel,
  FinancialLedgerTransactionModel,
} from '../models/financial-ledger.model.js';

import {
  approvalStatusValues,
  approvalTypeValues,
  chargeCatalogStatusValues,
  chargeHistoryActionValues,
  chargeRuleTypeValues,
  chargeSourceModuleValues,
  chargeStatusValues,
  financialNoteStatusValues,
  invoiceHistoryActionValues,
  invoiceStatusValues,
  ledgerEntryDirectionValues,
  ledgerTransactionStatusValues,
  packageEnrollmentStatusValues,
  packageStatusValues,
  packageUtilizationStatusValues,
  patientAccountStatusValues,
  paymentIntentStatusValues,
  paymentReversalStatusValues,
  paymentStatusValues,
  priceListStatusValues,
  rateStatusValues,
  refundRequestStatusValues,
  refundStatusValues,
} from '../models/billing.types.js';

import type {
  Migration,
} from './types.js';

export const chargeCatalogUnifiedBillingFoundationCollections = [
  'chargeCategories',
  'taxCategories',
  'chargeCatalog',
  'chargeCatalogVersions',
  'chargeRules',
  'priceLists',
  'priceListVersions',
  'serviceRates',
  'treatmentPackages',
  'treatmentPackageItems',
  'packageEnrollments',
  'packageUtilizations',
  'patientAccounts',
  'patientAccountStatusHistories',
  'accountCharges',
  'accountChargeHistories',
  'invoices',
  'invoiceLines',
  'invoiceStatusHistories',
  'creditNotes',
  'debitNotes',
  'discounts',
  'discountApprovals',
  'financialApprovalRequests',
  'paymentIntents',
  'payments',
  'paymentAllocations',
  'deposits',
  'refundRequests',
  'refunds',
  'paymentReversals',
  'financialLedgerAccounts',
  'financialLedgerTransactions',
  'financialLedgerEntries',
] as const satisfies readonly HospitalCollectionName[];

type BillingFoundationCollection =
  (typeof chargeCatalogUnifiedBillingFoundationCollections)[number];

const objectId = { bsonType: 'objectId' } as const;
const nullableObjectId = {
  bsonType: ['objectId', 'null'],
} as const;
const string = { bsonType: 'string' } as const;
const nullableString = {
  bsonType: ['string', 'null'],
} as const;
const date = { bsonType: 'date' } as const;
const nullableDate = {
  bsonType: ['date', 'null'],
} as const;
const number = { bsonType: 'number' } as const;
const boolean = { bsonType: 'bool' } as const;
const decimal = { bsonType: 'decimal' } as const;
const nullableDecimal = {
  bsonType: ['decimal', 'null'],
} as const;
const objectIdArray = {
  bsonType: 'array',
  items: objectId,
} as const;
const objectArray = {
  bsonType: 'array',
  items: { bsonType: 'object' },
} as const;

const commonProperties = {
  facilityId: objectId,
  transactionId: string,
  correlationId: string,
  schemaVersion: {
    ...number,
    minimum: 1,
  },
  version: {
    ...number,
    minimum: 0,
  },
  createdBy: objectId,
  updatedBy: objectId,
  createdAt: date,
  updatedAt: date,
} as const;

const commonRequired = [
  'facilityId',
  'transactionId',
  'correlationId',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
] as const;

function enumString(
  values: readonly string[],
): Record<string, unknown> {
  return {
    ...string,
    enum: [...values],
  };
}

function validator(
  required: readonly string[],
  properties: Record<string, unknown>,
): Record<string, unknown> {
  return {
    $jsonSchema: {
      bsonType: 'object',
      required: [
        ...commonRequired,
        ...required,
      ],
      properties: {
        _id: objectId,
        ...commonProperties,
        ...properties,
      },
    },
  };
}

const moneyProperties = {
  grossAmount: decimal,
  discountAmount: decimal,
  taxAmount: decimal,
  welfareAmount: decimal,
  payerAmount: decimal,
  patientAmount: decimal,
  netAmount: decimal,
} as const;

export const chargeCatalogUnifiedBillingFoundationValidators:
Readonly<
  Record<
    BillingFoundationCollection,
    Record<string, unknown>
  >
> = {
  chargeCategories: validator(
    ['code', 'name', 'clinical', 'status', 'activatedAt', 'activatedBy'],
    {
      code: string,
      parentCategoryId: nullableObjectId,
      name: string,
      description: nullableString,
      clinical: boolean,
      departmentId: nullableObjectId,
      serviceLineCode: nullableString,
      revenueAccountCode: nullableString,
      status: string,
      activatedAt: date,
      activatedBy: objectId,
      deactivatedAt: nullableDate,
      deactivatedBy: nullableObjectId,
      deactivationReason: nullableString,
    },
  ),
  taxCategories: validator(
    [
      'code',
      'name',
      'calculationMode',
      'ratePercentage',
      'roundingMode',
      'roundingScale',
      'exemptionReasonRequired',
      'effectiveFrom',
      'active',
    ],
    {
      code: string,
      name: string,
      calculationMode: string,
      ratePercentage: decimal,
      roundingMode: string,
      roundingScale: number,
      exemptionReasonRequired: boolean,
      effectiveFrom: date,
      effectiveThrough: nullableDate,
      active: boolean,
    },
  ),
  chargeCatalog: validator(
    [
      'chargeCode',
      'serviceCode',
      'name',
      'categoryId',
      'chargeType',
      'clinical',
      'defaultQuantity',
      'costAmount',
      'manualPostingAllowed',
      'recurringChargeAllowed',
      'timeBasedCharge',
      'effectiveFrom',
      'status',
      'currentVersion',
    ],
    {
      chargeCode: string,
      serviceCode: string,
      name: string,
      description: nullableString,
      categoryId: objectId,
      chargeType: string,
      clinical: boolean,
      departmentId: nullableObjectId,
      serviceLineCode: nullableString,
      revenueAccountCode: nullableString,
      ledgerAccountId: nullableObjectId,
      taxCategoryId: nullableObjectId,
      unitOfMeasureId: nullableObjectId,
      defaultQuantity: decimal,
      minimumQuantity: nullableDecimal,
      maximumQuantity: nullableDecimal,
      minimumPrice: nullableDecimal,
      maximumPrice: nullableDecimal,
      costAmount: decimal,
      manualPostingAllowed: boolean,
      recurringChargeAllowed: boolean,
      timeBasedCharge: boolean,
      effectiveFrom: date,
      effectiveThrough: nullableDate,
      status: enumString(chargeCatalogStatusValues),
      currentVersion: number,
      latestVersionId: nullableObjectId,
    },
  ),
  chargeCatalogVersions: validator(
    [
      'chargeCatalogItemId',
      'versionNumber',
      'chargeCode',
      'serviceCode',
      'name',
      'categoryId',
      'chargeType',
      'defaultQuantity',
      'costAmount',
      'effectiveFrom',
      'statusSnapshot',
      'changeReason',
      'recordedAt',
      'recordedBy',
    ],
    {
      chargeCatalogItemId: objectId,
      versionNumber: number,
      chargeCode: string,
      serviceCode: string,
      name: string,
      categoryId: objectId,
      chargeType: string,
      defaultQuantity: decimal,
      costAmount: decimal,
      effectiveFrom: date,
      effectiveThrough: nullableDate,
      statusSnapshot: enumString(chargeCatalogStatusValues),
      changeReason: string,
      recordedAt: date,
      recordedBy: objectId,
    },
  ),
  chargeRules: validator(
    [
      'ruleCode',
      'chargeCatalogItemId',
      'ruleType',
      'effectiveFrom',
      'active',
      'reason',
    ],
    {
      ruleCode: string,
      chargeCatalogItemId: objectId,
      ruleType: enumString(chargeRuleTypeValues),
      relatedChargeCatalogItemId: nullableObjectId,
      thresholdQuantity: nullableDecimal,
      thresholdAmount: nullableDecimal,
      effectiveFrom: date,
      effectiveThrough: nullableDate,
      active: boolean,
      reason: string,
    },
  ),
  priceLists: validator(
    [
      'code',
      'name',
      'priceListType',
      'currency',
      'afterHoursOnly',
      'effectiveFrom',
      'status',
      'priority',
      'currentVersion',
    ],
    {
      code: string,
      name: string,
      description: nullableString,
      priceListType: string,
      currency: string,
      patientCategoryCode: nullableString,
      payerCategoryCode: nullableString,
      payerOrganizationId: nullableObjectId,
      panelPlanId: nullableObjectId,
      departmentId: nullableObjectId,
      locationId: nullableObjectId,
      billingContext: nullableString,
      afterHoursOnly: boolean,
      effectiveFrom: date,
      effectiveThrough: nullableDate,
      status: enumString(priceListStatusValues),
      priority: number,
      currentVersion: number,
      latestVersionId: nullableObjectId,
    },
  ),
  priceListVersions: validator(
    [
      'priceListId',
      'versionNumber',
      'code',
      'name',
      'priceListType',
      'currency',
      'afterHoursOnly',
      'effectiveFrom',
      'statusSnapshot',
      'prioritySnapshot',
      'changeReason',
      'recordedAt',
      'recordedBy',
    ],
    {
      priceListId: objectId,
      versionNumber: number,
      code: string,
      name: string,
      priceListType: string,
      currency: string,
      afterHoursOnly: boolean,
      effectiveFrom: date,
      effectiveThrough: nullableDate,
      statusSnapshot: enumString(priceListStatusValues),
      prioritySnapshot: number,
      changeReason: string,
      recordedAt: date,
      recordedBy: objectId,
    },
  ),
  serviceRates: validator(
    [
      'rateCode',
      'chargeCatalogItemId',
      'chargeCatalogVersionId',
      'priceListId',
      'priceListVersionId',
      'amount',
      'currency',
      'afterHoursOnly',
      'effectiveFrom',
      'status',
    ],
    {
      rateCode: string,
      chargeCatalogItemId: objectId,
      chargeCatalogVersionId: objectId,
      priceListId: objectId,
      priceListVersionId: objectId,
      amount: decimal,
      minimumAmount: nullableDecimal,
      maximumAmount: nullableDecimal,
      currency: string,
      taxCategoryId: nullableObjectId,
      billingContext: nullableString,
      patientCategoryCode: nullableString,
      payerCategoryCode: nullableString,
      payerOrganizationId: nullableObjectId,
      panelPlanId: nullableObjectId,
      departmentId: nullableObjectId,
      locationId: nullableObjectId,
      afterHoursOnly: boolean,
      effectiveFrom: date,
      effectiveThrough: nullableDate,
      status: enumString(rateStatusValues),
      supersedesRateId: nullableObjectId,
    },
  ),
  treatmentPackages: validator(
    [
      'packageCode',
      'name',
      'packageType',
      'fixedPrice',
      'currency',
      'validityDays',
      'effectiveFrom',
      'status',
    ],
    {
      packageCode: string,
      name: string,
      description: nullableString,
      packageType: string,
      fixedPrice: decimal,
      currency: string,
      validityDays: number,
      payerOrganizationId: nullableObjectId,
      panelPlanId: nullableObjectId,
      patientCategoryCode: nullableString,
      billingContext: nullableString,
      effectiveFrom: date,
      effectiveThrough: nullableDate,
      status: enumString(packageStatusValues),
    },
  ),
  treatmentPackageItems: validator(
    [
      'treatmentPackageId',
      'lineNumber',
      'chargeCatalogItemId',
      'includedQuantity',
      'overageAllowed',
      'allocationAmount',
      'requiredComponent',
      'active',
    ],
    {
      treatmentPackageId: objectId,
      lineNumber: number,
      chargeCatalogItemId: objectId,
      includedQuantity: decimal,
      overageAllowed: boolean,
      overageRateId: nullableObjectId,
      allocationAmount: decimal,
      requiredComponent: boolean,
      active: boolean,
    },
  ),
  packageEnrollments: validator(
    [
      'enrollmentNumber',
      'patientId',
      'patientAccountId',
      'treatmentPackageId',
      'enrolledAt',
      'validFrom',
      'validThrough',
      'packagePriceSnapshot',
      'currency',
      'status',
    ],
    {
      enrollmentNumber: string,
      patientId: objectId,
      patientAccountId: objectId,
      treatmentPackageId: objectId,
      encounterId: nullableObjectId,
      admissionId: nullableObjectId,
      enrolledAt: date,
      validFrom: date,
      validThrough: date,
      packagePriceSnapshot: decimal,
      currency: string,
      status: enumString(packageEnrollmentStatusValues),
      cancellationReason: nullableString,
    },
  ),
  packageUtilizations: validator(
    [
      'operationKey',
      'packageEnrollmentId',
      'treatmentPackageItemId',
      'accountChargeId',
      'consumedQuantity',
      'overageQuantity',
      'status',
    ],
    {
      operationKey: string,
      packageEnrollmentId: objectId,
      treatmentPackageItemId: objectId,
      accountChargeId: objectId,
      consumedQuantity: decimal,
      overageQuantity: decimal,
      status: enumString(packageUtilizationStatusValues),
      consumedAt: nullableDate,
      reversedAt: nullableDate,
      reversalReason: nullableString,
    },
  ),
  patientAccounts: validator(
    [
      'accountNumber',
      'patientId',
      'accountType',
      'billingContext',
      'responsiblePartyType',
      'payerSnapshots',
      'currency',
      'grossCharges',
      'discountTotal',
      'taxTotal',
      'welfareTotal',
      'payerResponsibilityTotal',
      'patientResponsibilityTotal',
      'paymentsAppliedTotal',
      'creditsTotal',
      'writeOffTotal',
      'outstandingBalance',
      'refundableBalance',
      'status',
    ],
    {
      accountNumber: string,
      patientId: objectId,
      accountType: string,
      billingContext: string,
      registrationId: nullableObjectId,
      opdVisitId: nullableObjectId,
      encounterId: nullableObjectId,
      admissionId: nullableObjectId,
      responsiblePartyType: string,
      guarantorId: nullableObjectId,
      payerSnapshots: objectArray,
      currency: string,
      grossCharges: decimal,
      discountTotal: decimal,
      taxTotal: decimal,
      welfareTotal: decimal,
      payerResponsibilityTotal: decimal,
      patientResponsibilityTotal: decimal,
      paymentsAppliedTotal: decimal,
      creditsTotal: decimal,
      writeOffTotal: decimal,
      outstandingBalance: decimal,
      refundableBalance: decimal,
      status: enumString(patientAccountStatusValues),
      lockedAt: nullableDate,
      lockedBy: nullableObjectId,
      finalizedAt: nullableDate,
      finalizedBy: nullableObjectId,
    },
  ),
  patientAccountStatusHistories: validator(
    [
      'patientAccountId',
      'toStatus',
      'accountVersion',
      'reason',
      'changedAt',
      'changedBy',
    ],
    {
      patientAccountId: objectId,
      fromStatus: nullableString,
      toStatus: enumString(patientAccountStatusValues),
      accountVersion: number,
      reason: string,
      changedAt: date,
      changedBy: objectId,
      approvalRequestId: nullableObjectId,
    },
  ),
  accountCharges: validator(
    [
      'operationKey',
      'deterministicChargeKey',
      'patientAccountId',
      'patientId',
      'source',
      'chargeCatalogItemId',
      'chargeCatalogVersionId',
      'serviceRateId',
      'priceListId',
      'priceListVersionId',
      'chargeCodeSnapshot',
      'serviceCodeSnapshot',
      'chargeNameSnapshot',
      'categoryCodeSnapshot',
      'quantity',
      'originalUnitPrice',
      'authoritativeUnitPrice',
      'costAmountSnapshot',
      'currency',
      'status',
      'serviceFrom',
      ...Object.keys(moneyProperties),
    ],
    {
      operationKey: string,
      deterministicChargeKey: string,
      patientAccountId: objectId,
      patientId: objectId,
      registrationId: nullableObjectId,
      opdVisitId: nullableObjectId,
      encounterId: nullableObjectId,
      admissionId: nullableObjectId,
      source: {
        bsonType: 'object',
        required: [
          'sourceModule',
          'sourceRecordType',
          'sourceRecordId',
          'sourceOccurredAt',
        ],
        properties: {
          sourceModule: enumString(chargeSourceModuleValues),
          sourceRecordType: string,
          sourceRecordId: objectId,
          sourceLineId: nullableObjectId,
          sourceOccurredAt: date,
        },
      },
      chargeCatalogItemId: objectId,
      chargeCatalogVersionId: objectId,
      serviceRateId: objectId,
      priceListId: objectId,
      priceListVersionId: objectId,
      chargeCodeSnapshot: string,
      serviceCodeSnapshot: string,
      chargeNameSnapshot: string,
      categoryCodeSnapshot: string,
      quantity: decimal,
      originalUnitPrice: decimal,
      authoritativeUnitPrice: decimal,
      costAmountSnapshot: decimal,
      currency: string,
      ...moneyProperties,
      status: enumString(chargeStatusValues),
      packageEnrollmentId: nullableObjectId,
      treatmentPackageItemId: nullableObjectId,
      originalChargeId: nullableObjectId,
      replacementChargeId: nullableObjectId,
      approvalRequestIds: objectIdArray,
      postedAt: nullableDate,
      postedBy: nullableObjectId,
      lifecycleReason: nullableString,
      serviceFrom: date,
      serviceThrough: nullableDate,
    },
  ),
  accountChargeHistories: validator(
    [
      'accountChargeId',
      'action',
      'toStatus',
      'chargeVersion',
      'reason',
      'changedAt',
      'changedBy',
      'amountSnapshot',
    ],
    {
      accountChargeId: objectId,
      action: enumString(chargeHistoryActionValues),
      fromStatus: nullableString,
      toStatus: enumString(chargeStatusValues),
      chargeVersion: number,
      originalChargeId: nullableObjectId,
      replacementChargeId: nullableObjectId,
      reason: string,
      approvalRequestId: nullableObjectId,
      changedAt: date,
      changedBy: objectId,
      amountSnapshot: {
        bsonType: 'object',
        required: Object.keys(moneyProperties),
        properties: moneyProperties,
      },
    },
  ),
  invoices: validator(
    [
      'invoiceNumber',
      'patientAccountId',
      'patientId',
      'invoiceType',
      'currency',
      'status',
      'lineCount',
      'grossAmount',
      'discountAmount',
      'taxAmount',
      'welfareAmount',
      'payerAmount',
      'patientAmount',
      'netAmount',
      'paymentsAppliedAmount',
      'creditsAppliedAmount',
      'outstandingAmount',
      'refundableAmount',
      'taxSummary',
      'discountIds',
      'creditNoteIds',
      'debitNoteIds',
      'printableSnapshotVersion',
    ],
    {
      invoiceNumber: string,
      patientAccountId: objectId,
      patientId: objectId,
      invoiceType: string,
      currency: string,
      status: enumString(invoiceStatusValues),
      lineCount: number,
      grossAmount: decimal,
      discountAmount: decimal,
      taxAmount: decimal,
      welfareAmount: decimal,
      payerAmount: decimal,
      patientAmount: decimal,
      netAmount: decimal,
      paymentsAppliedAmount: decimal,
      creditsAppliedAmount: decimal,
      outstandingAmount: decimal,
      refundableAmount: decimal,
      issuedAt: nullableDate,
      finalizedAt: nullableDate,
      finalizedBy: nullableObjectId,
      originalInvoiceId: nullableObjectId,
      replacementInvoiceId: nullableObjectId,
      taxSummary: objectArray,
      discountIds: objectIdArray,
      creditNoteIds: objectIdArray,
      debitNoteIds: objectIdArray,
      printableSnapshotVersion: number,
    },
  ),
  invoiceLines: validator(
    [
      'invoiceId',
      'patientAccountId',
      'accountChargeId',
      'lineNumber',
      'sourceModuleSnapshot',
      'sourceRecordTypeSnapshot',
      'sourceRecordId',
      'chargeCatalogItemId',
      'chargeCatalogVersionId',
      'priceListId',
      'priceListVersionId',
      'serviceRateId',
      'chargeCodeSnapshot',
      'serviceCodeSnapshot',
      'chargeNameSnapshot',
      'categoryCodeSnapshot',
      'quantity',
      'originalRate',
      'authoritativeRate',
      'currency',
      'discountIds',
      ...Object.keys(moneyProperties),
    ],
    {
      invoiceId: objectId,
      patientAccountId: objectId,
      accountChargeId: objectId,
      lineNumber: number,
      sourceModuleSnapshot: string,
      sourceRecordTypeSnapshot: string,
      sourceRecordId: objectId,
      sourceLineId: nullableObjectId,
      chargeCatalogItemId: objectId,
      chargeCatalogVersionId: objectId,
      priceListId: objectId,
      priceListVersionId: objectId,
      serviceRateId: objectId,
      chargeCodeSnapshot: string,
      serviceCodeSnapshot: string,
      chargeNameSnapshot: string,
      categoryCodeSnapshot: string,
      quantity: decimal,
      originalRate: decimal,
      authoritativeRate: decimal,
      currency: string,
      ...moneyProperties,
      discountIds: objectIdArray,
    },
  ),
  invoiceStatusHistories: validator(
    [
      'invoiceId',
      'action',
      'toStatus',
      'invoiceVersion',
      'reason',
      'changedAt',
      'changedBy',
    ],
    {
      invoiceId: objectId,
      action: enumString(invoiceHistoryActionValues),
      fromStatus: nullableString,
      toStatus: enumString(invoiceStatusValues),
      invoiceVersion: number,
      reason: string,
      originalInvoiceId: nullableObjectId,
      replacementInvoiceId: nullableObjectId,
      changedAt: date,
      changedBy: objectId,
    },
  ),
  creditNotes: validator(
    [
      'noteNumber',
      'patientAccountId',
      'invoiceId',
      'patientId',
      'originalFinancialRecordId',
      'amount',
      'currency',
      'status',
      'reasonCode',
      'reason',
      'approvalRequestId',
      'affectedAccountChargeIds',
    ],
    {
      noteNumber: string,
      patientAccountId: objectId,
      invoiceId: objectId,
      patientId: objectId,
      originalFinancialRecordId: objectId,
      amount: decimal,
      currency: string,
      status: enumString(financialNoteStatusValues),
      reasonCode: string,
      reason: string,
      approvalRequestId: objectId,
      affectedAccountChargeIds: objectIdArray,
      postedAt: nullableDate,
      postedBy: nullableObjectId,
      reversedAt: nullableDate,
      reversedBy: nullableObjectId,
      reversalReason: nullableString,
    },
  ),
  debitNotes: validator(
    [
      'noteNumber',
      'patientAccountId',
      'invoiceId',
      'patientId',
      'originalFinancialRecordId',
      'amount',
      'currency',
      'status',
      'reasonCode',
      'reason',
      'approvalRequestId',
      'replacementAccountChargeIds',
    ],
    {
      noteNumber: string,
      patientAccountId: objectId,
      invoiceId: objectId,
      patientId: objectId,
      originalFinancialRecordId: objectId,
      amount: decimal,
      currency: string,
      status: enumString(financialNoteStatusValues),
      reasonCode: string,
      reason: string,
      approvalRequestId: objectId,
      replacementAccountChargeIds: objectIdArray,
      postedAt: nullableDate,
      postedBy: nullableObjectId,
      reversedAt: nullableDate,
      reversedBy: nullableObjectId,
      reversalReason: nullableString,
    },
  ),
  discounts: validator(
    [
      'discountNumber',
      'patientAccountId',
      'scope',
      'discountType',
      'requestedValue',
      'approvedAmount',
      'reasonCode',
      'reason',
      'requestedBy',
      'requestedAt',
      'approvalRequestId',
    ],
    {
      discountNumber: string,
      patientAccountId: objectId,
      invoiceId: nullableObjectId,
      invoiceLineId: nullableObjectId,
      accountChargeId: nullableObjectId,
      scope: string,
      discountType: string,
      requestedValue: decimal,
      approvedAmount: decimal,
      reasonCode: string,
      reason: string,
      requestedBy: objectId,
      requestedAt: date,
      approvalRequestId: objectId,
      appliedAt: nullableDate,
      appliedBy: nullableObjectId,
      reversedAt: nullableDate,
      reversedBy: nullableObjectId,
      reversalReason: nullableString,
    },
  ),
  discountApprovals: validator(
    [
      'discountId',
      'financialApprovalRequestId',
      'approvedAmount',
      'approvedPercentage',
      'status',
      'decidedBy',
      'decidedAt',
      'decisionReason',
    ],
    {
      discountId: objectId,
      financialApprovalRequestId: objectId,
      approvedAmount: decimal,
      approvedPercentage: decimal,
      status: enumString(approvalStatusValues),
      decidedBy: objectId,
      decidedAt: date,
      decisionReason: string,
    },
  ),
  financialApprovalRequests: validator(
    [
      'requestNumber',
      'operationKey',
      'approvalType',
      'entityType',
      'entityId',
      'amount',
      'thresholdAmountSnapshot',
      'requestedBy',
      'requestedAt',
      'reason',
      'status',
      'makerCheckerSatisfied',
    ],
    {
      requestNumber: string,
      operationKey: string,
      approvalType: enumString(approvalTypeValues),
      entityType: string,
      entityId: objectId,
      patientAccountId: nullableObjectId,
      amount: decimal,
      thresholdAmountSnapshot: decimal,
      requestedBy: objectId,
      requestedAt: date,
      reason: string,
      status: enumString(approvalStatusValues),
      decidedBy: nullableObjectId,
      decidedAt: nullableDate,
      decisionReason: nullableString,
      expiresAt: nullableDate,
      makerCheckerSatisfied: boolean,
    },
  ),
  paymentIntents: validator(
    [
      'operationKey',
      'intentNumber',
      'patientAccountId',
      'patientId',
      'paymentMethod',
      'amount',
      'currency',
      'status',
      'expiresAt',
    ],
    {
      operationKey: string,
      intentNumber: string,
      patientAccountId: objectId,
      patientId: objectId,
      invoiceId: nullableObjectId,
      cashierStaffId: nullableObjectId,
      cashShiftId: nullableObjectId,
      cashCounterId: nullableObjectId,
      paymentMethod: string,
      amount: decimal,
      currency: string,
      externalReference: nullableString,
      status: enumString(paymentIntentStatusValues),
      expiresAt: date,
      authorizedAt: nullableDate,
      completedPaymentId: nullableObjectId,
      failureCode: nullableString,
      failureMessage: nullableString,
    },
  ),
  payments: validator(
    [
      'operationKey',
      'receiptNumber',
      'patientAccountId',
      'patientId',
      'paymentMethod',
      'amount',
      'currency',
      'allocatedAmount',
      'unallocatedAmount',
      'refundedAmount',
      'status',
      'receivedAt',
    ],
    {
      operationKey: string,
      receiptNumber: string,
      paymentIntentId: nullableObjectId,
      patientAccountId: objectId,
      patientId: objectId,
      invoiceId: nullableObjectId,
      cashierStaffId: nullableObjectId,
      cashShiftId: nullableObjectId,
      cashCounterId: nullableObjectId,
      paymentMethod: string,
      amount: decimal,
      currency: string,
      externalReference: nullableString,
      allocatedAmount: decimal,
      unallocatedAmount: decimal,
      refundedAmount: decimal,
      status: enumString(paymentStatusValues),
      receivedAt: date,
      postedAt: nullableDate,
      postedBy: nullableObjectId,
      failureCode: nullableString,
      failureMessage: nullableString,
      reversalId: nullableObjectId,
    },
  ),
  paymentAllocations: validator(
    [
      'operationKey',
      'paymentId',
      'patientAccountId',
      'amount',
      'status',
      'allocatedAt',
      'allocatedBy',
    ],
    {
      operationKey: string,
      paymentId: objectId,
      patientAccountId: objectId,
      invoiceId: nullableObjectId,
      accountChargeId: nullableObjectId,
      amount: decimal,
      status: string,
      allocatedAt: date,
      allocatedBy: objectId,
      reversedAt: nullableDate,
      reversedBy: nullableObjectId,
      reversalReason: nullableString,
    },
  ),
  deposits: validator(
    [
      'depositNumber',
      'patientId',
      'paymentId',
      'originalAmount',
      'availableAmount',
      'appliedAmount',
      'refundedAmount',
      'currency',
      'status',
      'receivedAt',
    ],
    {
      depositNumber: string,
      patientId: objectId,
      patientAccountId: nullableObjectId,
      paymentId: objectId,
      originalAmount: decimal,
      availableAmount: decimal,
      appliedAmount: decimal,
      refundedAmount: decimal,
      currency: string,
      status: string,
      receivedAt: date,
      expiresAt: nullableDate,
    },
  ),
  refundRequests: validator(
    [
      'requestNumber',
      'operationKey',
      'patientAccountId',
      'patientId',
      'amount',
      'currency',
      'reasonCode',
      'reason',
      'approvalRequestId',
      'status',
    ],
    {
      requestNumber: string,
      operationKey: string,
      patientAccountId: objectId,
      patientId: objectId,
      paymentId: nullableObjectId,
      depositId: nullableObjectId,
      creditNoteId: nullableObjectId,
      amount: decimal,
      currency: string,
      reasonCode: string,
      reason: string,
      approvalRequestId: objectId,
      status: enumString(refundRequestStatusValues),
      completedRefundId: nullableObjectId,
    },
  ),
  refunds: validator(
    [
      'operationKey',
      'refundNumber',
      'refundRequestId',
      'patientAccountId',
      'patientId',
      'amount',
      'currency',
      'paymentMethod',
      'status',
    ],
    {
      operationKey: string,
      refundNumber: string,
      refundRequestId: objectId,
      patientAccountId: objectId,
      patientId: objectId,
      paymentId: nullableObjectId,
      depositId: nullableObjectId,
      amount: decimal,
      currency: string,
      paymentMethod: string,
      externalReference: nullableString,
      status: enumString(refundStatusValues),
      postedAt: nullableDate,
      postedBy: nullableObjectId,
      failureCode: nullableString,
      failureMessage: nullableString,
    },
  ),
  paymentReversals: validator(
    [
      'operationKey',
      'reversalNumber',
      'paymentId',
      'patientAccountId',
      'amount',
      'reasonCode',
      'reason',
      'approvalRequestId',
      'status',
    ],
    {
      operationKey: string,
      reversalNumber: string,
      paymentId: objectId,
      patientAccountId: objectId,
      amount: decimal,
      reasonCode: string,
      reason: string,
      approvalRequestId: objectId,
      status: enumString(paymentReversalStatusValues),
      postedAt: nullableDate,
      postedBy: nullableObjectId,
      failureCode: nullableString,
    },
  ),
  financialLedgerAccounts: validator(
    [
      'accountCode',
      'name',
      'accountType',
      'active',
      'allowDirectPosting',
      'sensitiveMarginAccount',
    ],
    {
      accountCode: string,
      name: string,
      accountType: string,
      parentAccountId: nullableObjectId,
      departmentId: nullableObjectId,
      serviceLineCode: nullableString,
      active: boolean,
      allowDirectPosting: boolean,
      sensitiveMarginAccount: boolean,
    },
  ),
  financialLedgerTransactions: validator(
    [
      'operationKey',
      'journalNumber',
      'sourceModule',
      'sourceEntityType',
      'sourceEntityId',
      'currency',
      'totalDebit',
      'totalCredit',
      'entryCount',
      'status',
      'postedAt',
      'postedBy',
      'description',
    ],
    {
      operationKey: string,
      journalNumber: string,
      sourceModule: string,
      sourceEntityType: string,
      sourceEntityId: objectId,
      patientId: nullableObjectId,
      patientAccountId: nullableObjectId,
      invoiceId: nullableObjectId,
      paymentId: nullableObjectId,
      cashShiftId: nullableObjectId,
      cashCounterId: nullableObjectId,
      currency: string,
      totalDebit: decimal,
      totalCredit: decimal,
      entryCount: number,
      status: enumString(ledgerTransactionStatusValues),
      postedAt: date,
      postedBy: objectId,
      description: string,
      reversalOfTransactionId: nullableObjectId,
      reversedByTransactionId: nullableObjectId,
      reversalReason: nullableString,
      closedPeriodCode: nullableString,
    },
  ),
  financialLedgerEntries: validator(
    [
      'ledgerTransactionId',
      'lineNumber',
      'ledgerAccountId',
      'ledgerAccountCodeSnapshot',
      'direction',
      'amount',
      'currency',
      'description',
      'postedAt',
    ],
    {
      ledgerTransactionId: objectId,
      lineNumber: number,
      ledgerAccountId: objectId,
      ledgerAccountCodeSnapshot: string,
      direction: enumString(ledgerEntryDirectionValues),
      amount: decimal,
      currency: string,
      patientId: nullableObjectId,
      patientAccountId: nullableObjectId,
      invoiceId: nullableObjectId,
      paymentId: nullableObjectId,
      departmentId: nullableObjectId,
      serviceLineCode: nullableString,
      chargeCatalogItemId: nullableObjectId,
      description: string,
      postedAt: date,
    },
  ),
};

const models = {
  chargeCategories: ChargeCategoryModel,
  taxCategories: TaxCategoryModel,
  chargeCatalog: ChargeCatalogModel,
  chargeCatalogVersions: ChargeCatalogVersionModel,
  chargeRules: ChargeRuleModel,
  priceLists: PriceListModel,
  priceListVersions: PriceListVersionModel,
  serviceRates: ServiceRateModel,
  treatmentPackages: TreatmentPackageModel,
  treatmentPackageItems: TreatmentPackageItemModel,
  packageEnrollments: PackageEnrollmentModel,
  packageUtilizations: PackageUtilizationModel,
  patientAccounts: PatientAccountModel,
  patientAccountStatusHistories:
    PatientAccountStatusHistoryModel,
  accountCharges: AccountChargeModel,
  accountChargeHistories: AccountChargeHistoryModel,
  invoices: InvoiceModel,
  invoiceLines: InvoiceLineModel,
  invoiceStatusHistories: InvoiceStatusHistoryModel,
  creditNotes: CreditNoteModel,
  debitNotes: DebitNoteModel,
  discounts: DiscountModel,
  discountApprovals: DiscountApprovalModel,
  financialApprovalRequests: FinancialApprovalRequestModel,
  paymentIntents: PaymentIntentModel,
  payments: PaymentModel,
  paymentAllocations: PaymentAllocationModel,
  deposits: DepositModel,
  refundRequests: RefundRequestModel,
  refunds: RefundModel,
  paymentReversals: PaymentReversalModel,
  financialLedgerAccounts: FinancialLedgerAccountModel,
  financialLedgerTransactions: FinancialLedgerTransactionModel,
  financialLedgerEntries: FinancialLedgerEntryModel,
} as const;

const expectedRetention: Readonly<
  Record<BillingFoundationCollection, CollectionRetention>
> = {
  chargeCategories: 'standard',
  taxCategories: 'standard',
  chargeCatalog: 'standard',
  chargeCatalogVersions: 'immutable',
  chargeRules: 'standard',
  priceLists: 'standard',
  priceListVersions: 'immutable',
  serviceRates: 'standard',
  treatmentPackages: 'standard',
  treatmentPackageItems: 'standard',
  packageEnrollments: 'standard',
  packageUtilizations: 'standard',
  patientAccounts: 'standard',
  patientAccountStatusHistories: 'immutable',
  accountCharges: 'standard',
  accountChargeHistories: 'immutable',
  invoices: 'standard',
  invoiceLines: 'standard',
  invoiceStatusHistories: 'immutable',
  creditNotes: 'standard',
  debitNotes: 'standard',
  discounts: 'standard',
  discountApprovals: 'standard',
  financialApprovalRequests: 'standard',
  paymentIntents: 'standard',
  payments: 'standard',
  paymentAllocations: 'standard',
  deposits: 'standard',
  refundRequests: 'standard',
  refunds: 'standard',
  paymentReversals: 'standard',
  financialLedgerAccounts: 'standard',
  financialLedgerTransactions: 'immutable',
  financialLedgerEntries: 'immutable',
};

const expectedDomain: Readonly<
  Record<BillingFoundationCollection, 'finance' | 'payers'>
> = {
  chargeCategories: 'finance',
  taxCategories: 'finance',
  chargeCatalog: 'finance',
  chargeCatalogVersions: 'finance',
  chargeRules: 'finance',
  priceLists: 'finance',
  priceListVersions: 'finance',
  serviceRates: 'finance',
  treatmentPackages: 'payers',
  treatmentPackageItems: 'payers',
  packageEnrollments: 'payers',
  packageUtilizations: 'payers',
  patientAccounts: 'finance',
  patientAccountStatusHistories: 'finance',
  accountCharges: 'finance',
  accountChargeHistories: 'finance',
  invoices: 'finance',
  invoiceLines: 'finance',
  invoiceStatusHistories: 'finance',
  creditNotes: 'finance',
  debitNotes: 'finance',
  discounts: 'finance',
  discountApprovals: 'finance',
  financialApprovalRequests: 'finance',
  paymentIntents: 'finance',
  payments: 'finance',
  paymentAllocations: 'finance',
  deposits: 'finance',
  refundRequests: 'finance',
  refunds: 'finance',
  paymentReversals: 'finance',
  financialLedgerAccounts: 'finance',
  financialLedgerTransactions: 'finance',
  financialLedgerEntries: 'finance',
};

async function ensureCollection(
  database: Db,
  name: BillingFoundationCollection,
): Promise<void> {
  const exists =
    (
      await database
        .listCollections({ name }, { nameOnly: true })
        .toArray()
    ).length > 0;
  const collectionValidator =
    chargeCatalogUnifiedBillingFoundationValidators[name];

  if (exists) {
    await database.command({
      collMod: name,
      validator: collectionValidator,
      validationLevel: 'strict',
      validationAction: 'error',
    });
  } else {
    await database.createCollection(name, {
      validator: collectionValidator,
      validationLevel: 'strict',
      validationAction: 'error',
    });
  }

  const collection = database.collection(name);
  const existingIndexes = await collection.indexes();

  for (const index of existingIndexes) {
    if (index.name !== '_id_') {
      await collection.dropIndex(index.name);
    }
  }

  const indexes = models[name].schema.indexes() as IndexDescription[];
  if (indexes.length > 0) {
    await collection.createIndexes(indexes);
  }
}

export const chargeCatalogUnifiedBillingFoundation: Migration = {
  id: '029-charge-catalog-unified-billing-foundation',
  description:
    'Create charge catalog, authoritative pricing, package, patient-account, charge, invoice, adjustment, payment-foundation, and operational-ledger collections',

  async up(database) {
    for (const collectionName of
      chargeCatalogUnifiedBillingFoundationCollections) {
      const spec = collectionSpecs.find(
        (candidate) => candidate.name === collectionName,
      );

      if (
        spec === undefined ||
        spec.domain !== expectedDomain[collectionName] ||
        !spec.facilityScoped ||
        spec.retention !== expectedRetention[collectionName]
      ) {
        throw new Error(
          `${collectionName} has an invalid unified-billing collection specification`,
        );
      }

      await ensureCollection(database, collectionName);
    }
  },
};