export const INVENTORY_CATEGORY_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'categoryCode',
  'name',
  'normalizedName',
  'categoryType',
  'parentCategoryId',
  'ancestorCategoryIds',
  'hierarchyDepth',
  'description',
  'displayOrder',
  'status',
  'activatedAt',
  'activatedBy',
  'deactivatedAt',
  'deactivatedBy',
  'transactionId',
  'correlationId',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const INVENTORY_CATEGORY_INTERNAL_SELECT = [
  INVENTORY_CATEGORY_STANDARD_SELECT,
  '+deactivationReason',
].join(' ');

export const INVENTORY_ITEM_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'itemCode',
  'name',
  'normalizedName',
  'itemType',
  'categoryId',
  'formularyItemId',
  'barcode',
  'manufacturerName',
  'description',
  'stockUnitId',
  'purchaseUnitId',
  'purchaseUnitToStockFactor',
  'issueUnitId',
  'issueUnitToStockFactor',
  'unitConversions',
  'allowFractionalStock',
  'batchTrackingRequired',
  'expiryTrackingRequired',
  'storageConditions',
  'minimumStorageTemperatureCelsius',
  'maximumStorageTemperatureCelsius',
  'reorderLevel',
  'minimumStockLevel',
  'maximumStockLevel',
  'safetyStockLevel',
  'nearExpiryWarningDays',
  'negativeStockAllowed',
  'controlledMedicine',
  'highAlert',
  'highValue',
  'valuationMethod',
  'preferredSupplierIds',
  'supplierCatalogueEntries.supplierId',
  'supplierCatalogueEntries.supplierItemCode',
  'supplierCatalogueEntries.supplierItemName',
  'supplierCatalogueEntries.purchaseUnitId',
  'supplierCatalogueEntries.purchaseUnitToStockFactor',
  'supplierCatalogueEntries.minimumOrderQuantity',
  'supplierCatalogueEntries.currency',
  'supplierCatalogueEntries.leadTimeDays',
  'supplierCatalogueEntries.preferred',
  'supplierCatalogueEntries.active',
  'status',
  'activatedAt',
  'activatedBy',
  'deactivatedAt',
  'deactivatedBy',
  'transactionId',
  'correlationId',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const INVENTORY_ITEM_COST_SELECT = [
  INVENTORY_ITEM_STANDARD_SELECT,
  '+supplierCatalogueEntries.lastQuotedUnitCost',
].join(' ');

export const INVENTORY_ITEM_INTERNAL_SELECT = [
  INVENTORY_ITEM_COST_SELECT,
  '+searchText',
  '+deactivationReason',
].join(' ');

export const INVENTORY_LOCATION_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'locationCode',
  'name',
  'normalizedName',
  'locationType',
  'parentLocationId',
  'ancestorLocationIds',
  'hierarchyDepth',
  'departmentId',
  'wardId',
  'servicePointId',
  'managerStaffId',
  'storageConditions',
  'supportsDispensing',
  'allowsControlledMedicine',
  'allowsGeneralStock',
  'stockOwnershipCode',
  'physicalAddress',
  'contactPhone',
  'displayOrder',
  'status',
  'activatedAt',
  'activatedBy',
  'deactivatedAt',
  'deactivatedBy',
  'transactionId',
  'correlationId',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const INVENTORY_LOCATION_INTERNAL_SELECT = [
  INVENTORY_LOCATION_STANDARD_SELECT,
  '+deactivationReason',
].join(' ');

export const SUPPLIER_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'supplierCode',
  'legalName',
  'normalizedLegalName',
  'tradingName',
  'defaultCurrency',
  'paymentTermsDays',
  'standardLeadTimeDays',
  'status',
  'activatedAt',
  'activatedBy',
  'suspendedAt',
  'suspendedBy',
  'deactivatedAt',
  'deactivatedBy',
  'transactionId',
  'correlationId',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const SUPPLIER_SENSITIVE_SELECT = [
  SUPPLIER_STANDARD_SELECT,
  'contacts',
  'addresses',
  '+registrationNumber',
  '+taxRegistrationNumber',
  '+salesTaxRegistrationNumber',
  '+drugSaleLicenseNumber',
  '+notes',
  '+suspensionReason',
  '+deactivationReason',
].join(' ');

export const INVENTORY_BATCH_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'itemId',
  'supplierId',
  'batchNumber',
  'manufacturerName',
  'manufacturerBatchNumber',
  'normalizedBatchNumber',
  'manufactureDate',
  'expiryDate',
  'sellingPrice',
  'currency',
  'goodsReceiptId',
  'goodsReceiptItemId',
  'inspectionStatus',
  'status',
  'quarantineAt',
  'quarantinedBy',
  'releasedFromQuarantineAt',
  'releasedFromQuarantineBy',
  'recallStatus',
  'recallReference',
  'recalledAt',
  'recalledBy',
  'blockedAt',
  'blockedBy',
  'enteredInErrorAt',
  'enteredInErrorBy',
  'transactionId',
  'correlationId',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');

export const INVENTORY_BATCH_COST_SELECT = [
  INVENTORY_BATCH_STANDARD_SELECT,
  '+costPrice',
].join(' ');

export const INVENTORY_BATCH_INTERNAL_SELECT = [
  INVENTORY_BATCH_COST_SELECT,
  '+quarantineReason',
  '+quarantineReleaseReason',
  '+recallReason',
  '+blockedReason',
  '+enteredInErrorReason',
].join(' ');

export const STOCK_BALANCE_STANDARD_SELECT = [
  '_id',
  'facilityId',
  'storeLocationId',
  'itemId',
  'batchId',
  'onHandQuantity',
  'availableQuantity',
  'reservedQuantity',
  'quarantinedQuantity',
  'damagedQuantity',
  'expiredQuantity',
  'inTransitQuantity',
  'lastMovementId',
  'lastMovementAt',
  'lastLedgerSequence',
  'lastReconciledAt',
  'projectionTransactionId',
  'correlationId',
  'schemaVersion',
  'version',
  'createdBy',
  'updatedBy',
  'createdAt',
  'updatedAt',
].join(' ');