import {
  toObjectId,
} from '@hospital-mis/database';

import type {
  CashMovementView,
  CreateCashMovementInput,
  DecideCashMovementInput,
  PaymentCashierActorContext,
  PaymentCashierListQuery,
  PaymentCashierPage,
  PostCashMovementInput,
} from '../payments-cashier-shifts.contracts.js';

import {
  CashCounterInactiveError,
  CashCounterNotFoundError,
  CashMovementNotFoundError,
  CashierShiftNotFoundError,
  CashierShiftNotOpenError,
  PaymentCashierAccessDeniedError,
  PaymentCashierConcurrencyError,
} from '../payments-cashier-shifts.errors.js';

import type {
  PaymentCashierAccessPolicyPort,
  PaymentCashierAuditPort,
  PaymentCashierOutboxPort,
  PaymentCashierRealtimePort,
  PaymentCashierSequencePort,
} from '../payments-cashier-shifts.ports.js';

import type {
  CashMovementRecord,
  PaymentCashierMongoSession,
} from '../payments-cashier-shifts.persistence.types.js';

import {
  projectCashMovement,
} from '../payments-cashier-shifts.projections.js';

import {
  PAYMENT_CASHIER_AUDIT_ACTIONS,
  PAYMENT_CASHIER_EVENT_TYPES,
  PAYMENT_CASHIER_LOCK_NAMESPACES,
  PAYMENT_CASHIER_REALTIME_EVENTS,
  PAYMENT_CASHIER_SEQUENCE_KEYS,
  PAYMENT_CASHIER_TRANSACTION_TYPES,
} from '../payments-cashier-shifts.operations.js';

import {
  normalizePaymentCashierText,
  paymentCashierLockKey,
} from '../payments-cashier-shifts.normalization.js';

import type {
  CashMovementControlRepositoryPort,
} from '../repositories/cash-movement.repository.js';

import type {
  CashierShiftExtendedRepositoryPort,
} from '../repositories/cashier-shift.repository.js';

import type {
  PaymentConfigurationRepository,
} from '../repositories/payment-configuration.repository.js';

import {
  PaymentCashierCommandSupport,
  type PaymentCashierCommandContext,
} from './payment-cashier-command-support.js';

export interface CashMovementServiceDependencies {
  movements: CashMovementControlRepositoryPort;
  shifts: CashierShiftExtendedRepositoryPort;
  configuration: PaymentConfigurationRepository;
  accessPolicy: PaymentCashierAccessPolicyPort;
  commandSupport: PaymentCashierCommandSupport;
  sequences: PaymentCashierSequencePort;
  audit: PaymentCashierAuditPort;
  outbox: PaymentCashierOutboxPort;
  realtime: PaymentCashierRealtimePort;
  clock: Readonly<{ now(): Date }>;
}

const systemGeneratedMovementTypes = new Set([
  'OPENING_FLOAT',
  'CASH_COLLECTION',
  'CASH_REFUND',
]);

const approvalRequiredMovementTypes = new Set([
  'CASH_PAID_OUT',
  'COUNTER_TRANSFER',
  'SHIFT_TRANSFER',
]);

function requireUpdated<T>(value: T | null): T {
  if (value === null) {
    throw new PaymentCashierConcurrencyError();
  }

  return value;
}

export class CashMovementService {
  public constructor(
    private readonly dependencies: CashMovementServiceDependencies,
  ) {}

  public async get(
    actor: PaymentCashierActorContext,
    movementId: string,
  ): Promise<CashMovementView> {
    const movement = await this.dependencies.movements.findById(
      actor.facilityId,
      movementId,
    );

    if (movement === null) {
      throw new CashMovementNotFoundError();
    }

    this.dependencies.accessPolicy.require({
      actor,
      action: 'CASH_MOVEMENT_READ',
      resourceFacilityId: actor.facilityId,
      counterId: movement.sourceCounterId?.toHexString() ??
        movement.destinationCounterId?.toHexString() ??
        null,
    });

    return projectCashMovement(movement);
  }

  public async list(
    actor: PaymentCashierActorContext,
    query: PaymentCashierListQuery,
  ): Promise<PaymentCashierPage<CashMovementView>> {
    this.dependencies.accessPolicy.require({
      actor,
      action: 'CASH_MOVEMENT_READ',
      resourceFacilityId: actor.facilityId,
      counterId: query.counterId,
    });

    const page = await this.dependencies.movements.list(
      actor.facilityId,
      query,
    );

    return {
      ...page,
      items: page.items.map(projectCashMovement),
    };
  }

  public async create(
    command: PaymentCashierCommandContext,
    input: CreateCashMovementInput,
  ): Promise<CashMovementView> {
    const { actor } = command;

    this.dependencies.accessPolicy.require({
      actor,
      action: 'CASH_MOVEMENT_CREATE',
      resourceFacilityId: actor.facilityId,
      counterId: input.sourceCounterId ?? input.destinationCounterId,
      cashierUserId: actor.userId,
    });

    if (systemGeneratedMovementTypes.has(input.movementType)) {
      throw new PaymentCashierAccessDeniedError(
        'Opening-float, collection, and refund cash movements are generated by their authoritative workflows',
      );
    }

    const requiresApproval = approvalRequiredMovementTypes.has(
      input.movementType,
    );
    const result = await this.dependencies.commandSupport.execute({
      operation: PAYMENT_CASHIER_TRANSACTION_TYPES.CREATE_CASH_MOVEMENT,
      command,
      payload: input,
      lockKeys: this.movementLockKeys(actor.facilityId, input),
      work: async ({ session, transactionId, operationKey }) => {
        await this.requireMovementScope(actor, input, session);
        const now = this.dependencies.clock.now();
        const movementNumber = await this.dependencies.sequences.next(
          actor.facilityId,
          PAYMENT_CASHIER_SEQUENCE_KEYS.CASH_MOVEMENT,
          now,
          session,
        );
        const approvalNumber = requiresApproval
          ? await this.dependencies.sequences.next(
              actor.facilityId,
              PAYMENT_CASHIER_SEQUENCE_KEYS.FINANCIAL_APPROVAL,
              now,
              session,
            )
          : movementNumber;
        const created = await this.dependencies.movements.createWithApproval(
          actor.facilityId,
          input,
          {
            operationKey,
            movementNumber,
            approvalOperationKey: `${operationKey}:approval`,
            approvalRequestNumber: approvalNumber,
            expectedCashEffect: this.expectedSourceCashEffect(input),
            requiresApproval,
            actorUserId: actor.userId,
            requestedAt: now,
            transactionId,
            correlationId: actor.correlationId,
          },
          session,
        );
        const view = projectCashMovement(created);

        await this.dependencies.commandSupport.appendHistory({
          actor,
          transactionId,
          entityType: 'CASH_MOVEMENT',
          entityId: view.id,
          action: requiresApproval ? 'APPROVAL_REQUESTED' : 'APPROVED',
          occurredAt: now,
          session,
          statusFrom: null,
          statusTo: view.status,
          amount: view.amount,
          currency: view.currency,
          reasonCode: view.reasonCode,
          reason: view.reason,
          cashCounterId: view.sourceCounterId ?? view.destinationCounterId,
          cashShiftId: view.sourceShiftId ?? view.destinationShiftId,
          metadata: {
            movementNumber: view.movementNumber,
            movementType: view.movementType,
          },
        });

        await this.writeEvent(
          actor,
          transactionId,
          now,
          created,
          PAYMENT_CASHIER_AUDIT_ACTIONS.CASH_MOVEMENT_CREATED,
          PAYMENT_CASHIER_EVENT_TYPES.CASH_MOVEMENT_CREATED,
          session,
        );

        return view;
      },
    });

    await this.publish(actor.facilityId, result);
    return result;
  }

  public async decide(
    command: PaymentCashierCommandContext,
    movementId: string,
    input: DecideCashMovementInput,
  ): Promise<CashMovementView> {
    const { actor } = command;
    const existing = await this.dependencies.movements.findById(
      actor.facilityId,
      movementId,
    );

    if (existing === null) {
      throw new CashMovementNotFoundError();
    }

    this.dependencies.accessPolicy.require({
      actor,
      action: 'CASH_MOVEMENT_APPROVE',
      resourceFacilityId: actor.facilityId,
      counterId: existing.sourceCounterId?.toHexString() ??
        existing.destinationCounterId?.toHexString() ??
        null,
      makerUserId: existing.requestedBy.toHexString(),
    });

    const result = await this.dependencies.commandSupport.execute({
      operation: PAYMENT_CASHIER_TRANSACTION_TYPES.DECIDE_CASH_MOVEMENT,
      command,
      payload: { movementId, ...input },
      lockKeys: [
        paymentCashierLockKey(
          PAYMENT_CASHIER_LOCK_NAMESPACES.CASH_MOVEMENT,
          actor.facilityId,
          movementId,
        ),
      ],
      work: async ({ session, transactionId }) => {
        const now = this.dependencies.clock.now();
        const decided = await this.dependencies.movements.decide(
          actor.facilityId,
          movementId,
          input.expectedVersion,
          input.decision,
          input.decisionReason,
          actor.userId,
          now,
          transactionId,
          actor.correlationId,
          session,
        );
        const view = projectCashMovement(decided);
        const approved = input.decision === 'APPROVE';

        await this.dependencies.commandSupport.appendHistory({
          actor,
          transactionId,
          entityType: 'CASH_MOVEMENT',
          entityId: view.id,
          action: approved ? 'APPROVED' : 'REJECTED',
          occurredAt: now,
          session,
          statusFrom: 'PENDING_APPROVAL',
          statusTo: view.status,
          amount: view.amount,
          currency: view.currency,
          reason: input.decisionReason,
          cashCounterId: view.sourceCounterId ?? view.destinationCounterId,
          cashShiftId: view.sourceShiftId ?? view.destinationShiftId,
        });

        await this.writeEvent(
          actor,
          transactionId,
          now,
          decided,
          approved
            ? PAYMENT_CASHIER_AUDIT_ACTIONS.CASH_MOVEMENT_APPROVED
            : PAYMENT_CASHIER_AUDIT_ACTIONS.CASH_MOVEMENT_REJECTED,
          PAYMENT_CASHIER_EVENT_TYPES.CASH_MOVEMENT_DECIDED,
          session,
        );

        return view;
      },
    });

    await this.publish(actor.facilityId, result);
    return result;
  }

  public async post(
    command: PaymentCashierCommandContext,
    movementId: string,
    input: PostCashMovementInput,
  ): Promise<CashMovementView> {
    const { actor } = command;
    const existing = await this.dependencies.movements.findById(
      actor.facilityId,
      movementId,
    );

    if (existing === null) {
      throw new CashMovementNotFoundError();
    }

    this.dependencies.accessPolicy.require({
      actor,
      action: 'CASH_MOVEMENT_POST',
      resourceFacilityId: actor.facilityId,
      counterId: existing.sourceCounterId?.toHexString() ??
        existing.destinationCounterId?.toHexString() ??
        null,
      makerUserId: existing.requestedBy.toHexString(),
    });

    const result = await this.dependencies.commandSupport.execute({
      operation: PAYMENT_CASHIER_TRANSACTION_TYPES.POST_CASH_MOVEMENT,
      command,
      payload: { movementId, ...input },
      lockKeys: [
        paymentCashierLockKey(
          PAYMENT_CASHIER_LOCK_NAMESPACES.CASH_MOVEMENT,
          actor.facilityId,
          movementId,
        ),
        ...(existing.sourceShiftId === null
          ? []
          : [
              paymentCashierLockKey(
                PAYMENT_CASHIER_LOCK_NAMESPACES.CASHIER_SHIFT,
                actor.facilityId,
                existing.sourceShiftId.toHexString(),
              ),
            ]),
        ...(existing.destinationShiftId === null
          ? []
          : [
              paymentCashierLockKey(
                PAYMENT_CASHIER_LOCK_NAMESPACES.CASHIER_SHIFT,
                actor.facilityId,
                existing.destinationShiftId.toHexString(),
              ),
            ]),
      ],
      work: async ({ session, transactionId }) => {
        const movement = await this.dependencies.movements.findById(
          actor.facilityId,
          movementId,
          session,
        );

        if (
          movement === null ||
          movement.version !== input.expectedVersion ||
          movement.status !== 'APPROVED'
        ) {
          throw new PaymentCashierConcurrencyError();
        }

        await this.requireStoredMovementScope(actor, movement, session);
        const now = this.dependencies.clock.now();
        const updated = requireUpdated(
          await this.dependencies.movements.update(
            actor.facilityId,
            movementId,
            movement.version,
            {
              status: 'POSTED',
              postedBy: toObjectId(actor.userId, 'actor.userId'),
              postedAt: now,
              updatedBy: toObjectId(actor.userId, 'actor.userId'),
              transactionId,
              correlationId: actor.correlationId,
            },
            session,
          ),
        );
        const view = projectCashMovement(updated);

        await this.dependencies.commandSupport.appendHistory({
          actor,
          transactionId,
          entityType: 'CASH_MOVEMENT',
          entityId: view.id,
          action: 'POSTED',
          occurredAt: now,
          session,
          statusFrom: 'APPROVED',
          statusTo: 'POSTED',
          amount: view.amount,
          currency: view.currency,
          reasonCode: view.reasonCode,
          reason: view.reason,
          cashCounterId: view.sourceCounterId ?? view.destinationCounterId,
          cashShiftId: view.sourceShiftId ?? view.destinationShiftId,
        });

        await this.writeEvent(
          actor,
          transactionId,
          now,
          updated,
          PAYMENT_CASHIER_AUDIT_ACTIONS.CASH_MOVEMENT_POSTED,
          PAYMENT_CASHIER_EVENT_TYPES.CASH_MOVEMENT_POSTED,
          session,
        );

        return view;
      },
    });

    await this.publish(actor.facilityId, result);
    return result;
  }

  private expectedSourceCashEffect(
    input: CreateCashMovementInput,
  ): string {
    return ['CASH_PAID_OUT', 'CASH_DROP', 'SAFE_DEPOSIT', 'COUNTER_TRANSFER', 'SHIFT_TRANSFER']
      .includes(input.movementType)
      ? `-${input.amount}`
      : input.amount;
  }

  private movementLockKeys(
    facilityId: string,
    input: CreateCashMovementInput,
  ): string[] {
    return [
      ...(input.sourceShiftId == null
        ? []
        : [
            paymentCashierLockKey(
              PAYMENT_CASHIER_LOCK_NAMESPACES.CASHIER_SHIFT,
              facilityId,
              input.sourceShiftId,
            ),
          ]),
      ...(input.destinationShiftId == null
        ? []
        : [
            paymentCashierLockKey(
              PAYMENT_CASHIER_LOCK_NAMESPACES.CASHIER_SHIFT,
              facilityId,
              input.destinationShiftId,
            ),
          ]),
    ];
  }

  private async requireMovementScope(
    actor: PaymentCashierActorContext,
    input: CreateCashMovementInput,
    session: PaymentCashierMongoSession,
  ): Promise<void> {
    if (input.sourceCounterId != null) {
      await this.requireCounterShift(
        actor,
        input.sourceCounterId,
        input.sourceShiftId ?? null,
        session,
      );
    }

    if (input.destinationCounterId != null && input.destinationShiftId != null) {
      await this.requireCounterShift(
        actor,
        input.destinationCounterId,
        input.destinationShiftId,
        session,
        true,
      );
    }
  }

  private async requireStoredMovementScope(
    actor: PaymentCashierActorContext,
    movement: CashMovementRecord,
    session: PaymentCashierMongoSession,
  ): Promise<void> {
    if (movement.sourceCounterId !== null) {
      await this.requireCounterShift(
        actor,
        movement.sourceCounterId.toHexString(),
        movement.sourceShiftId?.toHexString() ?? null,
        session,
      );
    }

    if (
      movement.destinationCounterId !== null &&
      movement.destinationShiftId !== null
    ) {
      await this.requireCounterShift(
        actor,
        movement.destinationCounterId.toHexString(),
        movement.destinationShiftId.toHexString(),
        session,
        true,
      );
    }
  }

  private async requireCounterShift(
    actor: PaymentCashierActorContext,
    counterId: string,
    shiftId: string | null,
    session: PaymentCashierMongoSession,
    destination = false,
  ): Promise<void> {
    const counter = await this.dependencies.configuration.findCounterById(
      actor.facilityId,
      counterId,
      session,
    );

    if (counter === null) {
      throw new CashCounterNotFoundError();
    }

    if (!counter.active) {
      throw new CashCounterInactiveError();
    }

    if (shiftId === null) {
      if (!destination) {
        throw new CashierShiftNotOpenError();
      }

      return;
    }

    const shift = await this.dependencies.shifts.findById(
      actor.facilityId,
      shiftId,
      session,
    );

    if (shift === null) {
      throw new CashierShiftNotFoundError();
    }

    if (
      shift.status !== 'OPEN' ||
      shift.cashCounterId.toHexString() !== counterId
    ) {
      throw new CashierShiftNotOpenError();
    }
  }

  private async writeEvent(
    actor: PaymentCashierActorContext,
    transactionId: string,
    occurredAt: Date,
    movement: CashMovementRecord,
    auditAction: string,
    eventType: string,
    session: PaymentCashierMongoSession,
  ): Promise<void> {
    const view = projectCashMovement(movement);

    await Promise.all([
      this.dependencies.audit.record(
        {
          facilityId: actor.facilityId,
          actorUserId: actor.userId,
          actorStaffId: actor.staffId,
          action: auditAction,
          entityType: 'CASH_MOVEMENT',
          entityId: view.id,
          reason: normalizePaymentCashierText(view.reason),
          before: null,
          after: view as unknown as Record<string, unknown>,
          correlationId: actor.correlationId,
          transactionId,
          ipAddress: actor.ipAddress,
          userAgent: actor.userAgent,
        },
        session,
      ),
      this.dependencies.outbox.publish(
        {
          facilityId: actor.facilityId,
          aggregateType: 'CASH_MOVEMENT',
          aggregateId: view.id,
          eventType,
          payload: {
            movementId: view.id,
            movementNumber: view.movementNumber,
            movementType: view.movementType,
            status: view.status,
            sourceCounterId: view.sourceCounterId,
            destinationCounterId: view.destinationCounterId,
          },
          correlationId: actor.correlationId,
          transactionId,
          occurredAt,
        },
        session,
      ),
    ]);
  }

  private async publish(
    facilityId: string,
    view: CashMovementView,
  ): Promise<void> {
    await this.dependencies.realtime.publishMinimumNecessary({
      facilityId,
      eventType: PAYMENT_CASHIER_REALTIME_EVENTS.CASH_MOVEMENT_CHANGED,
      entityId: view.id,
      counterId: view.sourceCounterId ?? view.destinationCounterId,
      shiftId: view.sourceShiftId ?? view.destinationShiftId,
      status: view.status,
      occurredAt: this.dependencies.clock.now().toISOString(),
    });
  }
}