export type CollectionRetention =
  | 'standard'
  | 'immutable'
  | 'temporary'
  | 'derived';

export interface CollectionSpec {
  name: string;
  domain: string;
  facilityScoped: boolean;
  retention: CollectionRetention;
  schemaVersion: number;
}

type CollectionSpecRow = readonly [
  name: string,
  domain: string,
  facilityScoped: boolean,
  retention: CollectionRetention,
  schemaVersion: number,
];

const collectionSpecRows = [
  ['facilities', 'platform', false, 'standard', 1],
  ['departments', 'platform', true, 'standard', 1],
  ['users', 'platform', true, 'standard', 1],
  ['staff', 'platform', true, 'standard', 1],
  ['roles', 'platform', true, 'standard', 1],
  ['permissions', 'platform', false, 'standard', 1],
  ['userRoles', 'platform', true, 'standard', 1],
  ['rolePermissions', 'platform', true, 'standard', 1],
  ['sessions', 'platform', true, 'standard', 1],
  ['refreshTokens', 'platform', true, 'standard', 1],
  ['loginAttempts', 'platform', true, 'standard', 1],
  ['securityEvents', 'platform', true, 'standard', 1],
  ['settingDefinitions', 'platform', false, 'standard', 1],
  ['systemSettings', 'platform', false, 'standard', 1],
  ['systemSettingVersions', 'platform', false, 'immutable', 1],
  ['numberSequences', 'platform', true, 'standard', 1],
  ['attachments', 'platform', true, 'standard', 1],
  ['auditLogs', 'platform', true, 'immutable', 1],
  ['applicationTransactions', 'platform', true, 'standard', 1],
  ['applicationTransactionSteps', 'platform', true, 'standard', 1],
  ['idempotencyKeys', 'platform', true, 'standard', 1],
  ['operationLocks', 'platform', true, 'standard', 1],
  ['outboxEvents', 'platform', true, 'standard', 1],
  ['backgroundJobs', 'platform', true, 'standard', 1],
  ['reconciliationRuns', 'platform', true, 'standard', 1],
  ['reconciliationIssues', 'platform', true, 'standard', 1],
  ['notifications', 'platform', true, 'standard', 1],
  ['reportJobs', 'platform', true, 'standard', 1],
  ['reportArtifacts', 'platform', true, 'standard', 1],
  ['patients', 'patient', true, 'standard', 1],
  ['patientIdentifiers', 'patient', true, 'standard', 1],
  ['guardians', 'patient', true, 'standard', 1],
  ['patientGuardians', 'patient', true, 'standard', 1],
  ['patientContacts', 'patient', true, 'standard', 1],
  ['patientAddresses', 'patient', true, 'standard', 1],
  ['patientAlerts', 'patient', true, 'standard', 1],
  ['patientMergeCandidates', 'patient', true, 'standard', 1],
  ['patientMerges', 'patient', true, 'standard', 1],
  ['opdClinics', 'patient', true, 'standard', 1],
  ['servicePoints', 'patient', true, 'standard', 1],
  ['serviceCounters', 'patient', true, 'standard', 1],
  ['registrations', 'patient', true, 'standard', 1],
  ['opdVisits', 'patient', true, 'standard', 1],
  ['queueDefinitions', 'patient', true, 'standard', 1],
  ['queueTokens', 'patient', true, 'standard', 1],
  ['queueStatusHistories', 'patient', true, 'immutable', 1],
  ['encounters', 'clinical', true, 'standard', 1],
  ['encounterStatusHistories', 'clinical', true, 'immutable', 1],
  ['clinicalNotes', 'clinical', true, 'standard', 1],
  ['clinicalNoteVersions', 'clinical', true, 'immutable', 1],
  ['diagnoses', 'clinical', true, 'standard', 1],
  ['encounterDiagnoses', 'clinical', true, 'standard', 1],
  ['patientProblems', 'clinical', true, 'standard', 1],
  ['patientProblemVersions', 'clinical', true, 'immutable', 1],
  ['allergies', 'clinical', true, 'standard', 1],
  ['patientAllergies', 'clinical', true, 'standard', 1],
  ['patientAllergyVersions', 'clinical', true, 'immutable', 1],
  ['clinicalReferrals', 'clinical', true, 'immutable', 1],
  ['medicines', 'clinical', true, 'standard', 1],
  ['medicineForms', 'clinical', true, 'standard', 1],
  ['medicineRoutes', 'clinical', true, 'standard', 1],
  ['medicineStrengths', 'clinical', true, 'standard', 1],
  ['prescriptionFrequencies', 'clinical', true, 'standard', 1],
  ['formularyItems', 'clinical', true, 'standard', 1],
  ['prescriptions', 'clinical', true, 'standard', 1],
  ['prescriptionItems', 'clinical', true, 'standard', 1],
  ['prescriptionSafetyWarnings', 'clinical', true, 'standard', 1],
  ['prescriptionStatusHistories', 'clinical', true, 'immutable', 1],
  ['labTestCategories', 'laboratory', true, 'standard', 1],
  ['labTests', 'laboratory', true, 'standard', 1],
  ['labOrders', 'laboratory', true, 'standard', 1],
  ['labOrderItems', 'laboratory', true, 'standard', 1],
  ['labOrderStatusHistories', 'laboratory', true, 'immutable', 1],
  ['labSpecimens', 'laboratory', true, 'standard', 1],
  ['labSpecimenStatusHistories', 'laboratory', true, 'immutable', 1],
  ['labResults', 'laboratory', true, 'standard', 1],
  ['labResultVersions', 'laboratory', true, 'immutable', 1],
  [
    'labCriticalResultCommunications',
    'laboratory',
    true,
    'immutable',
    1,
  ],
  ['radiologyModalities', 'radiology', true, 'standard', 1],
  ['radiologyProcedures', 'radiology', true, 'standard', 1],
  ['radiologyOrders', 'radiology', true, 'standard', 1],
  ['radiologyOrderItems', 'radiology', true, 'standard', 1],
  [
    'radiologyOrderStatusHistories',
    'radiology',
    true,
    'immutable',
    1,
  ],
  [
    'radiologyOrderItemStatusHistories',
    'radiology',
    true,
    'immutable',
    1,
  ],
  ['radiologyResources', 'radiology', true, 'standard', 1],
  ['radiologyAppointments', 'radiology', true, 'standard', 1],
  [
    'radiologyResourceReservations',
    'radiology',
    true,
    'standard',
    1,
  ],
  ['radiologySafetyScreenings', 'radiology', true, 'standard', 1],
  ['radiologyExaminations', 'radiology', true, 'standard', 1],
  ['radiologyImagingStudies', 'radiology', true, 'standard', 1],
  ['radiologyImagingSeries', 'radiology', true, 'standard', 1],
  ['radiologyReports', 'radiology', true, 'standard', 1],
  [
    'radiologyReportVersions',
    'radiology',
    true,
    'immutable',
    1,
  ],
  [
    'radiologyCriticalFindingCommunications',
    'radiology',
    true,
    'immutable',
    1,
  ],
  ['admissionRecommendations', 'clinical', true, 'standard', 1],
  ['dischargeSummaries', 'clinical', true, 'standard', 1],
  ['dischargeSummaryVersions', 'clinical', true, 'immutable', 1],
  ['wards', 'inpatient', true, 'standard', 1],
  ['rooms', 'inpatient', true, 'standard', 1],
  ['beds', 'inpatient', true, 'standard', 1],
  ['bedRates', 'inpatient', true, 'standard', 1],
  ['bedRateVersions', 'inpatient', true, 'immutable', 1],
  ['bedHolds', 'inpatient', true, 'standard', 1],
  ['admissions', 'inpatient', true, 'standard', 1],
  ['admissionStatusHistories', 'inpatient', true, 'immutable', 1],
  ['admissionBedAssignments', 'inpatient', true, 'standard', 1],
  ['bedStatusHistories', 'inpatient', true, 'immutable', 1],
  ['bedChargeSegments', 'inpatient', true, 'standard', 1],
  ['discharges', 'inpatient', true, 'standard', 1],
  ['vitalSigns', 'inpatient', true, 'standard', 1],
  ['vitalSignAmendments', 'inpatient', true, 'immutable', 1],
  ['nursingNotes', 'inpatient', true, 'standard', 1],
  ['nursingNoteVersions', 'inpatient', true, 'immutable', 1],
  ['medicationSchedules', 'inpatient', true, 'standard', 1],
  ['medicationAdministrations', 'inpatient', true, 'standard', 1],
  [
    'medicationAdministrationAmendments',
    'inpatient',
    true,
    'immutable',
    1,
  ],
  ['wardHandovers', 'inpatient', true, 'standard', 1],
  ['nursingEntryAmendments', 'inpatient', true, 'immutable', 1],
  ['inventoryItems', 'inventory', true, 'standard', 1],
  ['inventoryCategories', 'inventory', true, 'standard', 1],
  ['unitsOfMeasure', 'inventory', true, 'standard', 1],
  ['suppliers', 'inventory', true, 'standard', 1],
  ['storeLocations', 'inventory', true, 'standard', 1],
  ['purchaseRequisitions', 'inventory', true, 'standard', 1],
  ['purchaseRequisitionItems', 'inventory', true, 'standard', 1],
  [
    'procurementApprovalHistories',
    'inventory',
    true,
    'immutable',
    1,
  ],
  ['purchaseOrders', 'inventory', true, 'standard', 1],
  ['purchaseOrderItems', 'inventory', true, 'standard', 1],
  ['goodsReceipts', 'inventory', true, 'standard', 1],
  ['goodsReceiptItems', 'inventory', true, 'standard', 1],
  ['purchaseInvoices', 'inventory', true, 'standard', 1],
  ['inventoryBatches', 'inventory', true, 'standard', 1],
  ['stockBalances', 'inventory', true, 'standard', 1],
  ['stockMovements', 'inventory', true, 'immutable', 1],
  ['stockTransfers', 'inventory', true, 'standard', 1],
  ['stockTransferItems', 'inventory', true, 'standard', 1],
  ['stockReservations', 'inventory', true, 'standard', 1],
  ['stockReservationItems', 'inventory', true, 'standard', 1],
  ['stockAdjustments', 'inventory', true, 'standard', 1],
  ['physicalStockCounts', 'inventory', true, 'standard', 1],
  ['physicalStockCountItems', 'inventory', true, 'standard', 1],
  ['productRecalls', 'inventory', true, 'standard', 1],
  ['productRecallItems', 'inventory', true, 'standard', 1],
  ['dispensations', 'inventory', true, 'standard', 1],
  ['dispensationItems', 'inventory', true, 'standard', 1],
  ['dispensationStatusHistories', 'inventory', true, 'immutable', 1],
  ['pharmacyReviewEvents', 'inventory', true, 'immutable', 1],
  ['dispensationSubstitutions', 'inventory', true, 'standard', 1],
  [
    'controlledMedicineRegisterEntries',
    'inventory',
    true,
    'immutable',
    1,
  ],
  ['dispensingLabels', 'inventory', true, 'standard', 1],
  ['dispensingLabelPrints', 'inventory', true, 'immutable', 1],
  ['pharmacyCounsellingRecords', 'inventory', true, 'standard', 1],
  ['dispensationReversals', 'inventory', true, 'standard', 1],
  ['patientReturns', 'inventory', true, 'standard', 1],
  ['patientReturnItems', 'inventory', true, 'standard', 1],
  ['supplierReturns', 'inventory', true, 'standard', 1],
  ['supplierReturnItems', 'inventory', true, 'standard', 1],
  ['reorderRules', 'inventory', true, 'standard', 1],
  ['chargeCatalog', 'finance', true, 'standard', 1],
  ['priceLists', 'finance', true, 'standard', 1],
  ['priceListVersions', 'finance', true, 'immutable', 1],
  ['serviceRates', 'finance', true, 'standard', 1],
  ['patientAccounts', 'finance', true, 'standard', 1],
  ['accountCharges', 'finance', true, 'standard', 1],
  ['invoices', 'finance', true, 'standard', 1],
  ['invoiceLines', 'finance', true, 'standard', 1],
  ['payments', 'finance', true, 'standard', 1],
  ['paymentAllocations', 'finance', true, 'standard', 1],
  ['deposits', 'finance', true, 'standard', 1],
  ['refunds', 'finance', true, 'standard', 1],
  ['creditNotes', 'finance', true, 'standard', 1],
  ['discounts', 'finance', true, 'standard', 1],
  ['discountApprovals', 'finance', true, 'standard', 1],
  ['cashCounters', 'finance', true, 'standard', 1],
  ['cashShifts', 'finance', true, 'standard', 1],
  ['shiftReconciliations', 'finance', true, 'standard', 1],
  ['financialLedgerAccounts', 'finance', true, 'standard', 1],
  [
    'financialLedgerTransactions',
    'finance',
    true,
    'immutable',
    1,
  ],
  ['financialLedgerEntries', 'finance', true, 'immutable', 1],
  ['payerOrganizations', 'payers', true, 'standard', 1],
  ['panelPrograms', 'payers', true, 'standard', 1],
  ['panelPlans', 'payers', true, 'standard', 1],
  ['patientCoverages', 'payers', true, 'standard', 1],
  ['preauthorizations', 'payers', true, 'standard', 1],
  ['treatmentPackages', 'payers', true, 'standard', 1],
  ['treatmentPackageItems', 'payers', true, 'standard', 1],
  ['packageEnrollments', 'payers', true, 'standard', 1],
  ['packageUtilizations', 'payers', true, 'standard', 1],
  ['claims', 'payers', true, 'standard', 1],
  ['claimLines', 'payers', true, 'standard', 1],
  ['claimDocuments', 'payers', true, 'standard', 1],
  ['claimStatusHistories', 'payers', true, 'immutable', 1],
  ['claimPayments', 'payers', true, 'standard', 1],
  ['assistanceFunds', 'assistance', true, 'standard', 1],
  ['fundTransactions', 'assistance', true, 'immutable', 1],
  ['assistanceApplications', 'assistance', true, 'standard', 1],
  ['assistanceApprovals', 'assistance', true, 'standard', 1],
  ['invoiceFundAllocations', 'assistance', true, 'standard', 1],
  ['fundAllocationReversals', 'assistance', true, 'standard', 1],
  ['consultantAgreements', 'assistance', true, 'standard', 1],
  ['consultantAgreementRules', 'assistance', true, 'standard', 1],
  ['consultantRevenueEntries', 'assistance', true, 'standard', 1],
  ['consultantSettlements', 'assistance', true, 'standard', 1],
  ['consultantSettlementItems', 'assistance', true, 'standard', 1],
  ['dailyOperationalSummaries', 'reporting', true, 'standard', 1],
  ['dailyFinancialSummaries', 'reporting', true, 'standard', 1],
  ['dailyInventorySummaries', 'reporting', true, 'standard', 1],
  ['bedOccupancySnapshots', 'reporting', true, 'standard', 1],
  ['queuePerformanceSummaries', 'reporting', true, 'standard', 1],
  ['consultantRevenueSummaries', 'reporting', true, 'standard', 1],
  ['panelReceivableSnapshots', 'reporting', true, 'standard', 1],
  ['inventoryValuationSnapshots', 'reporting', true, 'standard', 1],
  ['nursingAssessments', 'inpatient', true, 'standard', 1],
  [
    'nursingAssessmentVersions',
    'inpatient',
    true,
    'immutable',
    1,
  ],
  ['nursingCarePlans', 'inpatient', true, 'standard', 1],
  [
    'nursingCarePlanVersions',
    'inpatient',
    true,
    'immutable',
    1,
  ],
  ['nursingTasks', 'inpatient', true, 'standard', 1],
  ['intakeOutputEntries', 'inpatient', true, 'standard', 1],
  ['nursingDevices', 'inpatient', true, 'standard', 1],
  [
    'nursingDeviceObservations',
    'inpatient',
    true,
    'immutable',
    1,
  ],
] as const satisfies readonly CollectionSpecRow[];

export type HospitalCollectionName =
  (typeof collectionSpecRows)[number][0];

export const collectionSpecs = collectionSpecRows.map(
  ([
    name,
    domain,
    facilityScoped,
    retention,
    schemaVersion,
  ]) => ({
    name,
    domain,
    facilityScoped,
    retention,
    schemaVersion,
  }),
) as readonly (CollectionSpec & {
  name: HospitalCollectionName;
})[];