export type CollectionRetention = 'standard' | 'immutable' | 'temporary' | 'derived';
export interface CollectionSpec {
  name: string;
  domain: string;
  facilityScoped: boolean;
  retention: CollectionRetention;
  schemaVersion: number;
}
export const collectionSpecs = [
  {
    name: 'facilities',
    domain: 'platform',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'departments',
    domain: 'platform',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'users',
    domain: 'platform',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'staff',
    domain: 'platform',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'roles',
    domain: 'platform',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'permissions',
    domain: 'platform',
    facilityScoped: false,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'userRoles',
    domain: 'platform',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'rolePermissions',
    domain: 'platform',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'sessions',
    domain: 'platform',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'refreshTokens',
    domain: 'platform',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'loginAttempts',
    domain: 'platform',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'securityEvents',
    domain: 'platform',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'systemSettings',
    domain: 'platform',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'numberSequences',
    domain: 'platform',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'attachments',
    domain: 'platform',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'auditLogs',
    domain: 'platform',
    facilityScoped: true,
    retention: 'immutable',
    schemaVersion: 1,
  },
  {
    name: 'applicationTransactions',
    domain: 'platform',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'applicationTransactionSteps',
    domain: 'platform',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'idempotencyKeys',
    domain: 'platform',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'operationLocks',
    domain: 'platform',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'outboxEvents',
    domain: 'platform',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'backgroundJobs',
    domain: 'platform',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'reconciliationRuns',
    domain: 'platform',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'reconciliationIssues',
    domain: 'platform',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'notifications',
    domain: 'platform',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'reportJobs',
    domain: 'platform',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'reportArtifacts',
    domain: 'platform',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'patients',
    domain: 'patient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'patientIdentifiers',
    domain: 'patient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'guardians',
    domain: 'patient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'patientGuardians',
    domain: 'patient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'patientContacts',
    domain: 'patient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'patientAddresses',
    domain: 'patient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'patientAlerts',
    domain: 'patient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'patientMergeCandidates',
    domain: 'patient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'patientMerges',
    domain: 'patient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'registrations',
    domain: 'patient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'opdVisits',
    domain: 'patient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'queueDefinitions',
    domain: 'patient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'queueTokens',
    domain: 'patient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'queueStatusHistories',
    domain: 'patient',
    facilityScoped: true,
    retention: 'immutable',
    schemaVersion: 1,
  },
  {
    name: 'encounters',
    domain: 'clinical',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'clinicalNotes',
    domain: 'clinical',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'clinicalNoteVersions',
    domain: 'clinical',
    facilityScoped: true,
    retention: 'immutable',
    schemaVersion: 1,
  },
  {
    name: 'diagnoses',
    domain: 'clinical',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'encounterDiagnoses',
    domain: 'clinical',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'allergies',
    domain: 'clinical',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'patientAllergies',
    domain: 'clinical',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'medicines',
    domain: 'clinical',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'medicineForms',
    domain: 'clinical',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'medicineStrengths',
    domain: 'clinical',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'prescriptionFrequencies',
    domain: 'clinical',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'prescriptions',
    domain: 'clinical',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'prescriptionItems',
    domain: 'clinical',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'prescriptionStatusHistories',
    domain: 'clinical',
    facilityScoped: true,
    retention: 'immutable',
    schemaVersion: 1,
  },
  {
    name: 'labTests',
    domain: 'clinical',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'labOrders',
    domain: 'clinical',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'labOrderItems',
    domain: 'clinical',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'labResults',
    domain: 'clinical',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'labResultVersions',
    domain: 'clinical',
    facilityScoped: true,
    retention: 'immutable',
    schemaVersion: 1,
  },
  {
    name: 'radiologyProcedures',
    domain: 'clinical',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'radiologyOrders',
    domain: 'clinical',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'radiologyReports',
    domain: 'clinical',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'radiologyReportVersions',
    domain: 'clinical',
    facilityScoped: true,
    retention: 'immutable',
    schemaVersion: 1,
  },
  {
    name: 'admissionRecommendations',
    domain: 'clinical',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'dischargeSummaries',
    domain: 'clinical',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'dischargeSummaryVersions',
    domain: 'clinical',
    facilityScoped: true,
    retention: 'immutable',
    schemaVersion: 1,
  },
  {
    name: 'wards',
    domain: 'inpatient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'rooms',
    domain: 'inpatient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'beds',
    domain: 'inpatient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'bedRates',
    domain: 'inpatient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'bedRateVersions',
    domain: 'inpatient',
    facilityScoped: true,
    retention: 'immutable',
    schemaVersion: 1,
  },
  {
    name: 'bedHolds',
    domain: 'inpatient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'admissions',
    domain: 'inpatient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'admissionBedAssignments',
    domain: 'inpatient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'bedStatusHistories',
    domain: 'inpatient',
    facilityScoped: true,
    retention: 'immutable',
    schemaVersion: 1,
  },
  {
    name: 'bedChargeSegments',
    domain: 'inpatient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'discharges',
    domain: 'inpatient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'vitalSigns',
    domain: 'inpatient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'vitalSignAmendments',
    domain: 'inpatient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'nursingNotes',
    domain: 'inpatient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'nursingNoteVersions',
    domain: 'inpatient',
    facilityScoped: true,
    retention: 'immutable',
    schemaVersion: 1,
  },
  {
    name: 'medicationSchedules',
    domain: 'inpatient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'medicationAdministrations',
    domain: 'inpatient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'medicationAdministrationAmendments',
    domain: 'inpatient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'wardHandovers',
    domain: 'inpatient',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'inventoryItems',
    domain: 'inventory',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'inventoryCategories',
    domain: 'inventory',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'unitsOfMeasure',
    domain: 'inventory',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'suppliers',
    domain: 'inventory',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'storeLocations',
    domain: 'inventory',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'purchaseOrders',
    domain: 'inventory',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'purchaseOrderItems',
    domain: 'inventory',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'goodsReceipts',
    domain: 'inventory',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'goodsReceiptItems',
    domain: 'inventory',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'purchaseInvoices',
    domain: 'inventory',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'inventoryBatches',
    domain: 'inventory',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'stockBalances',
    domain: 'inventory',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'stockMovements',
    domain: 'inventory',
    facilityScoped: true,
    retention: 'immutable',
    schemaVersion: 1,
  },
  {
    name: 'stockTransfers',
    domain: 'inventory',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'stockTransferItems',
    domain: 'inventory',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'stockAdjustments',
    domain: 'inventory',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'physicalStockCounts',
    domain: 'inventory',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'physicalStockCountItems',
    domain: 'inventory',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'dispensations',
    domain: 'inventory',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'dispensationItems',
    domain: 'inventory',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'patientReturns',
    domain: 'inventory',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'patientReturnItems',
    domain: 'inventory',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'supplierReturns',
    domain: 'inventory',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'supplierReturnItems',
    domain: 'inventory',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'reorderRules',
    domain: 'inventory',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'chargeCatalog',
    domain: 'finance',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'priceLists',
    domain: 'finance',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'priceListVersions',
    domain: 'finance',
    facilityScoped: true,
    retention: 'immutable',
    schemaVersion: 1,
  },
  {
    name: 'serviceRates',
    domain: 'finance',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'patientAccounts',
    domain: 'finance',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'accountCharges',
    domain: 'finance',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'invoices',
    domain: 'finance',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'invoiceLines',
    domain: 'finance',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'payments',
    domain: 'finance',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'paymentAllocations',
    domain: 'finance',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'deposits',
    domain: 'finance',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'refunds',
    domain: 'finance',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'creditNotes',
    domain: 'finance',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'discounts',
    domain: 'finance',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'discountApprovals',
    domain: 'finance',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'cashCounters',
    domain: 'finance',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'cashShifts',
    domain: 'finance',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'shiftReconciliations',
    domain: 'finance',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'financialLedgerAccounts',
    domain: 'finance',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'financialLedgerTransactions',
    domain: 'finance',
    facilityScoped: true,
    retention: 'immutable',
    schemaVersion: 1,
  },
  {
    name: 'financialLedgerEntries',
    domain: 'finance',
    facilityScoped: true,
    retention: 'immutable',
    schemaVersion: 1,
  },
  {
    name: 'payerOrganizations',
    domain: 'payers',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'panelPrograms',
    domain: 'payers',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'panelPlans',
    domain: 'payers',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'patientCoverages',
    domain: 'payers',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'preauthorizations',
    domain: 'payers',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'treatmentPackages',
    domain: 'payers',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'treatmentPackageItems',
    domain: 'payers',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'packageEnrollments',
    domain: 'payers',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'packageUtilizations',
    domain: 'payers',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'claims',
    domain: 'payers',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'claimLines',
    domain: 'payers',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'claimDocuments',
    domain: 'payers',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'claimStatusHistories',
    domain: 'payers',
    facilityScoped: true,
    retention: 'immutable',
    schemaVersion: 1,
  },
  {
    name: 'claimPayments',
    domain: 'payers',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'assistanceFunds',
    domain: 'assistance',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'fundTransactions',
    domain: 'assistance',
    facilityScoped: true,
    retention: 'immutable',
    schemaVersion: 1,
  },
  {
    name: 'assistanceApplications',
    domain: 'assistance',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'assistanceApprovals',
    domain: 'assistance',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'invoiceFundAllocations',
    domain: 'assistance',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'fundAllocationReversals',
    domain: 'assistance',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'consultantAgreements',
    domain: 'assistance',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'consultantAgreementRules',
    domain: 'assistance',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'consultantRevenueEntries',
    domain: 'assistance',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'consultantSettlements',
    domain: 'assistance',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'consultantSettlementItems',
    domain: 'assistance',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'dailyOperationalSummaries',
    domain: 'reporting',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'dailyFinancialSummaries',
    domain: 'reporting',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'dailyInventorySummaries',
    domain: 'reporting',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'bedOccupancySnapshots',
    domain: 'reporting',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'queuePerformanceSummaries',
    domain: 'reporting',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'consultantRevenueSummaries',
    domain: 'reporting',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'panelReceivableSnapshots',
    domain: 'reporting',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
  {
    name: 'inventoryValuationSnapshots',
    domain: 'reporting',
    facilityScoped: true,
    retention: 'standard',
    schemaVersion: 1,
  },
] as const satisfies readonly CollectionSpec[];

export type HospitalCollectionName = (typeof collectionSpecs)[number]['name'];
