import Decimal from 'decimal.js'; import { Decimal128, ObjectId, type ClientSession } from 'mongodb';
import type { FinancialActor, RequestApprovalInput, DecideApprovalInput, ReverseChargeInput, AdjustChargeInput, WriteOffInput } from '../unified-billing-final.contracts.js';
import { UnifiedBillingFinancialRepository } from '../repositories/unified-billing-financial.repository.js';
type Runtime={withTransaction<T>(work:(session:ClientSession)=>Promise<T>):Promise<T>; audit(session:ClientSession,event:Record<string,unknown>):Promise<void>; outbox(session:ClientSession,event:Record<string,unknown>):Promise<void>; now():Date;};
const need=(a:FinancialActor,p:string)=>{if(!a.permissions.has(p))throw new Error(`Missing permission ${p}`)}; const positive=(v:string)=>{const d=new Decimal(v);if(!d.isPositive())throw new Error('Amount must be positive');return d};
export class UnifiedBillingFinancialControlService {
 constructor(private readonly repo:UnifiedBillingFinancialRepository,private readonly runtime:Runtime){}
 async requestApproval(actor:FinancialActor,input:RequestApprovalInput){need(actor,'billing.approvals.request');positive(input.amount);return this.runtime.withTransaction(async s=>{const now=this.runtime.now(),_id=new ObjectId();const doc={_id,facilityId:new ObjectId(actor.facilityId),...input,amount:input.amount,status:'PENDING',requestedByUserId:new ObjectId(actor.userId),requestedByStaffId:actor.staffId?new ObjectId(actor.staffId):null,requestedAt:now,version:0,schemaVersion:1,createdAt:now,updatedAt:now};await this.repo.insertApproval(doc,s);await this.runtime.audit(s,{action:'BILLING_APPROVAL_REQUESTED',entityId:_id.toHexString(),actorId:actor.userId,facilityId:actor.facilityId,reason:input.reason});await this.runtime.outbox(s,{eventType:'billing.approval.requested',aggregateId:_id.toHexString(),facilityId:actor.facilityId});return {...doc,_id:_id.toHexString()};});}
 async decideApproval(actor:FinancialActor,input:DecideApprovalInput){need(actor,'billing.approvals.decide');return this.runtime.withTransaction(async s=>{const now=this.runtime.now();const current=await this.repo.approvals().findOne({_id:new ObjectId(input.approvalId),facilityId:new ObjectId(actor.facilityId)},{session:s});if(!current)throw new Error('Approval not found');if(String(current['requestedByUserId'])===actor.userId)throw new Error('Maker cannot approve own request');const status=input.decision==='APPROVE'?'APPROVED':'REJECTED';const updated=await this.repo.decideApproval(actor.facilityId,input.approvalId,input.expectedVersion,{status,decidedByUserId:new ObjectId(actor.userId),decidedAt:now,decisionReason:input.reason,updatedAt:now},s);if(!updated)throw new Error('Approval changed concurrently');await this.runtime.audit(s,{action:`BILLING_APPROVAL_${status}`,entityId:input.approvalId,actorId:actor.userId,facilityId:actor.facilityId,reason:input.reason});return updated;});}
 async reverseCharge(actor:FinancialActor,input:ReverseChargeInput){need(actor,'billing.charges.reverse');return this.runtime.withTransaction(async s=>{const charges=this.repo['db'].collection('accountCharges');const charge=await charges.findOne({_id:new ObjectId(input.chargeId),facilityId:new ObjectId(actor.facilityId)},{session:s});if(!charge)throw new Error('Charge not found');const original=new Decimal(charge['netAmount'].toString());const amount=input.amount?positive(input.amount):original.mul(new Decimal(input.quantity!)).div(new Decimal(charge['quantity'].toString()));if(amount.gt(original))throw new Error('Reversal exceeds remaining charge');const now=this.runtime.now(),_id=new ObjectId();await charges.insertOne({_id,facilityId:charge['facilityId'],accountId:charge['accountId'],patientId:charge['patientId'],sourceModule:'UNIFIED_BILLING',sourceType:'CHARGE_REVERSAL',sourceRecordId:charge['_id'],originalChargeId:charge['_id'],chargeCode:charge['chargeCode'],quantity:Decimal128.fromString('-1'),grossAmount:Decimal128.fromString(amount.neg().toFixed(2)),discountAmount:Decimal128.fromString('0'),taxAmount:Decimal128.fromString('0'),netAmount:Decimal128.fromString(amount.neg().toFixed(2)),patientResponsibilityAmount:Decimal128.fromString(amount.neg().toFixed(2)),payerResponsibilityAmount:Decimal128.fromString('0'),status:'REVERSED',operationKey:input.idempotencyKey,reasonCode:input.reasonCode,reason:input.reason,createdByUserId:new ObjectId(actor.userId),version:0,schemaVersion:1,createdAt:now,updatedAt:now},{session:s});await this.runtime.audit(s,{action:'BILLING_CHARGE_REVERSED',entityId:_id.toHexString(),actorId:actor.userId,facilityId:actor.facilityId,reason:input.reason});return {_id:_id.toHexString(),amount:amount.toFixed(2)};});}
 async adjustCharge(actor:FinancialActor,input:AdjustChargeInput){need(actor,'billing.charges.adjust');positive(input.discountAmount);return this.runtime.withTransaction(async s=>{const now=this.runtime.now(),_id=new ObjectId();await this.repo['db'].collection('chargeAdjustments').insertOne({_id,facilityId:new ObjectId(actor.facilityId),chargeId:new ObjectId(input.chargeId),...input,discountAmount:Decimal128.fromString(input.discountAmount),createdByUserId:new ObjectId(actor.userId),status:'POSTED',version:0,schemaVersion:1,createdAt:now,updatedAt:now},{session:s});await this.runtime.audit(s,{action:'BILLING_CHARGE_ADJUSTED',entityId:_id.toHexString(),actorId:actor.userId,facilityId:actor.facilityId,reason:input.reason});return {_id:_id.toHexString()};});}
 async writeOff(actor:FinancialActor,input:WriteOffInput){need(actor,'billing.writeoffs.post');positive(input.amount);return this.runtime.withTransaction(async s=>{const now=this.runtime.now(),_id=new ObjectId();await this.repo['db'].collection('accountWriteOffs').insertOne({_id,facilityId:new ObjectId(actor.facilityId),accountId:new ObjectId(input.accountId),invoiceId:input.invoiceId?new ObjectId(input.invoiceId):null,amount:Decimal128.fromString(input.amount),reasonCode:input.reasonCode,reason:input.reason,approvalId:new ObjectId(input.approvalId),operationKey:input.idempotencyKey,status:'POSTED',createdByUserId:new ObjectId(actor.userId),version:0,schemaVersion:1,createdAt:now,updatedAt:now},{session:s});await this.runtime.audit(s,{action:'BILLING_WRITE_OFF_POSTED',entityId:_id.toHexString(),actorId:actor.userId,facilityId:actor.facilityId,reason:input.reason});return {_id:_id.toHexString()};});}
}