import { ObjectId,type Document } from 'mongodb'; import type { BillingReportQuery,ReconciliationResult,RecoveryResult } from '../unified-billing-final.contracts.js'; import { UnifiedBillingFinancialRepository } from '../repositories/unified-billing-financial.repository.js';
const amount=(rows:Document[])=>rows[0]?.['total']?.toString?.()??'0.00';
export class UnifiedBillingReportingRecoveryService {constructor(private readonly repo:UnifiedBillingFinancialRepository){}
 async chargeActivity(q:BillingReportQuery){const filter:Document={facilityId:new ObjectId(q.facilityId),createdAt:{$gte:new Date(q.from),$lt:new Date(q.to)}};if(q.departmentId)filter['departmentId']=new ObjectId(q.departmentId);if(q.sourceModule)filter['sourceModule']=q.sourceModule;if(q.status)filter['status']=q.status;return this.repo.find('accountCharges',filter,(q.page-1)*q.pageSize,q.pageSize);}
 async revenueByCode(q:BillingReportQuery){return this.repo.aggregate('invoiceLines',[{$match:{facilityId:new ObjectId(q.facilityId),createdAt:{$gte:new Date(q.from),$lt:new Date(q.to)}}},{$group:{_id:{chargeCode:'$chargeCode',departmentId:'$departmentId'},gross:{$sum:'$grossAmount'},discount:{$sum:'$discountAmount'},tax:{$sum:'$taxAmount'},net:{$sum:'$netAmount'},count:{$sum:1}}},{$sort:{net:-1}}]);}
 async aging(facilityId:string,asOf=new Date()){return this.repo.aggregate('invoices',[{$match:{facilityId:new ObjectId(facilityId),status:{$in:['FINALIZED','PARTIALLY_PAID']},outstandingAmount:{$gt:0}}},{$addFields:{ageDays:{$dateDiff:{startDate:'$finalizedAt',endDate:asOf,unit:'day'}}}},{$bucket:{groupBy:'$ageDays',boundaries:[0,31,61,91,181,100000],default:'UNKNOWN',output:{amount:{$sum:'$outstandingAmount'},accountCount:{$sum:1}}}}]);}
 async reconciliation(q:BillingReportQuery):Promise<ReconciliationResult>{const match={facilityId:new ObjectId(q.facilityId),createdAt:{$gte:new Date(q.from),$lt:new Date(q.to)}};const sum=async(c:string,f:string)=>amount(await this.repo.aggregate(c,[{$match:match},{$group:{_id:null,total:{$sum:`$${f}`}}}]));const charges=await sum('accountCharges','netAmount'),invoiced=await sum('invoices','netAmount'),payments=await sum('payments','amount'),credits=await sum('creditNotes','amount'),refunds=await sum('refunds','amount'),writeOffs=await sum('accountWriteOffs','amount');const outstanding=await sum('patientAccounts','outstandingBalance');const discrepancies:string[]=[];return {facilityId:q.facilityId,from:q.from,to:q.to,charges,invoiced,payments,credits,refunds,writeOffs,outstanding,balanced:discrepancies.length===0,discrepancies};}
 async recoverFailed(limit=100):Promise<RecoveryResult>{const rows=await this.repo.find('transactionJournals',{module:'UNIFIED_BILLING',status:{$in:['FAILED','PENDING_RECOVERY']}},0,limit);let recovered=0,failed=0,skipped=0;for(const row of rows){try{const operationKey=String(row['operationKey']??'');if(!operationKey){skipped++;continue;}const already=await this.repo['db'].collection('accountCharges').findOne({operationKey});await this.repo['db'].collection('transactionJournals').updateOne({_id:row['_id']},{$set:{status:already?'COMPLETED':'RETRY_REQUIRED',recoveredAt:new Date(),updatedAt:new Date()},$inc:{version:1}});recovered++;}catch{failed++;}}return {scanned:rows.length,recovered,failed,skipped};}
 async expireStaleDrafts(before:Date){const invoices=await this.repo['db'].collection('invoices').updateMany({status:'DRAFT',createdAt:{$lt:before}},{$set:{status:'CANCELLED',cancelReason:'STALE_DRAFT_EXPIRED',cancelledAt:new Date(),updatedAt:new Date()},$inc:{version:1}});const approvals=await this.repo.approvals().updateMany({status:'PENDING',expiresAt:{$lt:new Date()}},{$set:{status:'EXPIRED',updatedAt:new Date()},$inc:{version:1}});return {invoices:invoices.modifiedCount,approvals:approvals.modifiedCount};}
}